RedRoverSchool/JenkinsQA_06

src/test/java/school/redrover/Folder4Test.java, src/test/java/school/redrover/model/DeleteFolderPage.java, src/test/java/school/redrover/model/MainPage.java
=> AT 04.05 | Folder > Delete Folder

src/test/java/school/redrover/Folder4Test.java
=> AT 04.05 | Folder> Cancel deleting folder

src/test/java/school/redrover/PipelineProject8Test.java
https://trello.com/c/03FJImhL/1459-0002-new-item-create-pipeline-project-with-incorrect-name
=> RF 00.02| New Item > Create Pipeline Project with incorrect name

src/test/java/school/redrover/PipelineProject5Test.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF 02.04 PipelineProjectPage refactoring POM

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/ManageJenkinsPage.java
https://trello.com/c/ajrSHD9P/1479-at-0902-manage-jenkins-search-settings-tools-and-actions
=> AT 09.02 | Manage Jenkins > Search settings > Tools and actions

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/MultiConfigurationTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/MultiConfigurationProjectPage.java
- refactor clickJobDropdownMenu method in MainPage
- add testBuildNowDropDownMenuMultiConfigurationProject to MultiConfigurationTest
- add clickJobDropdownMenuBuildNow, clickDashboard, getJobBuildStatus methods to MainPage to implement POM
[Trello](https://trello.com/c/1wN3dudF/1410-at-0304-multi-configuration-build-now-user-can-build-a-multi-configuration-project-by-selecting-this-action-from-the-drop-down-m)
=> AT 03.04 | Multi-Configuration > Build now > User can build a Multi-Configuration project by selecting this action from the drop-down 

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/MainPage.java
Refactoring in two methods: openAdminDropdownMenu();  openTabFromAdminDropdownMenu.
Removed assert in the method and @‌FindBy annotation
https://trello.com/c/0YoE5nDa/1488-rf-1704-page-header-refactoring-admin-dropdownmenu
=> RF 17.04 | Page-header > Refactoring Admin DropdownMenu

src/test/java/school/redrover/FreestyleProject4Test.java
=> RF 01.03 | Freestyle project > Build project with Boolean parameter / ERRfix01

src/test/java/school/redrover/Folder8Test.java
add testCreatePipelineProjectWithoutDescriptionInFolder()
AT: https://trello.com/c/uvmEV6vg
TC: https://trello.com/c/YHgRjk1l
=> AT 04.07 | Folder > Create Pipeline Project without description in Folder

src/test/java/school/redrover/MultiConfigurationProject4Test.java
=> RF 00.03 | New Item > Multi - Configuration project >Create Multi-Сonfiguration project. Negative test-case

src/test/java/school/redrover/UserProfileTest.java, src/test/java/school/redrover/model/CreateUserPage.java, src/test/java/school/redrover/model/ManageJenkinsPage.java, src/test/java/school/redrover/model/NewJobPage.java, src/test/java/school/redrover/model/StatusUserPage.java
RF 09.05 | POM |  Dashboard > Manage Jenkins > Manage Users > Change the user profile > Update description for User on the User Profile page
https://trello.com/c/uxZLauBM
=> RF 09.05 | POM | Manage Users > Change the user profile > Update description for User

src/test/java/school/redrover/CreateMultibranchPipeline1Test.java, src/test/java/school/redrover/Folder6Test.java, src/test/java/school/redrover/MultibranchPipeline26Test.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/MultibranchPipelinePage.java
Removed @FindBy
https://trello.com/c/ftwiMMuK
=> AT 04.08 | Folder > CreateFolder

src/test/java/school/redrover/FreestyleProjectAllTest.java
=> AT 01.01 | Freestyle project > View project page > Rename project from view page

src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/0Sbkxv5Y/1518-rf-delete-findby-and-pagefactory
=> delete FindBy and PageFactory

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/v63lgdFY/1513-rf-freestyleprojecttest-combining-tests
=> RF FreestyleProjectTest

src/test/java/school/redrover/FreestyleProject16Test.java, src/test/java/school/redrover/model/FreestyleProjectPage.java
[RF] - https://trello.com/c/efVJsVSE/1516-rf-deleting-annotations-findby
=> Deleting annotations @FindBy

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/HRNSgnCG/1537-rf-0000-new-item-freestyle-project-createfreestyleprojectwithinvalidname
=> RF 00.01 | | New Item > Freestyle Project > CreateFreestyleProjectWithInvalidName

src/test/java/school/redrover/MyViewsTest.java, src/test/java/school/redrover/model/MyViewsPage.java
https://trello.com/c/P8Iw7oo2/1510-rf-1101-my-view-refactoring-class-and-tests-to-pom
=> RF 11.01 | My Views > refactoring class and tests to POM

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/FolderPage.java, src/test/java/school/redrover/model/NewJobPage.java, src/test/java/school/redrover/model/ProjectPage.java
https://trello.com/c/NIPl9P7Z/1004-at-0408-folder-create-multiconfiguration-project-in-folder
=> AT 04.08 | Folder > Create Multiconfiguration project in Folder

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/rTPSPDqE/1542-rf-testcreatednewbuild
=> RF testCreatedNewBuild

src/test/java/school/redrover/MultiConfiguration3Test.java
=> RF 03.01 | Multi-Configuration project > add description>POM

src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/xTwVICta/1544-rf-0000-delete-findby-in-mainpage
=> RF 00.00 | Delete FindBy in MainPage

src/test/java/school/redrover/tests/ConfigurationFolderTest.java, src/test/java/school/redrover/tests/ConfigureFolderTest.java
=> RF 04.04 | Configuration Folder test- Class restoration.

src/test/java/school/redrover/MyViewsTest.java, src/test/java/school/redrover/model/MyViewsPage.java
AT 11.03 |Views > New View >Edit View> Edit My View Description with POM 
AT - https://trello.com/c/3qPJ5WHK/1546-at-1103-views-new-view-edit-view-edit-my-view-description
TC - https://trello.com/c/uK5Zk6WK/1545-tc-1103-views-new-view-edit-view-edit-my-view-description
=> AT 11.03 |Views > New View >Edit View> Edit My View Description 

src/test/java/school/redrover/OrganizationFolderTest.java
Convert testCreateOrganizationFolder() to POM
RF - https://trello.com/c/zCnh6SNd/1552-rf-testcreateorganizationfolder-to-pom
=> RF | testCreateOrganizationFolder() to POM

src/test/java/school/redrover/ConfigurationFolderTest.java
=> RF 04.04 | Configure Folder test-Location update

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectConfigPage.java
=> RF 01.05 | FreestyleProjectTest > testPreviewDescription + add 2 methods into FreestyleProjectConfigPage

src/test/java/school/redrover/OrganizationFolderTest.java
Convert testRenameOrganizationFolder() to POM
RF - https://trello.com/c/5mx1sf2v/1560-rf-0601-convert-testrenameorganizationfolder-to-pom
=> RF 06.01 | Convert testRenameOrganizationFolder() to POM

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF 01.05 | FreestyleProjectTest > modify testPreviewDescription

src/test/java/school/redrover/FooterJenkinsVersionTest.java, src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/MultiConfigProject26Test.java, src/test/java/school/redrover/MultiConfigurationProject2Test.java, src/test/java/school/redrover/MultiConfigurationProject4Test.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/MultiConfigurationTest.java, src/test/java/school/redrover/MyViewsTest.java, src/test/java/school/redrover/NewItemTest.java, src/test/java/school/redrover/NewProject3Test.java, src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/TestMainPage.java, src/test/java/school/redrover/UserProfileTest.java, src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/ConfigurePage.java, src/test/java/school/redrover/model/FreestyleProjectPage.java, src/test/java/school/redrover/model/JobPage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/NewViewFolderPage.java, src/test/java/school/redrover/model/ViewFolderPage.java, src/test/java/school/redrover/model/ViewPage.java, src/test/java/school/redrover/tests/BuildTest.java
https://trello.com/c/u8q1t0Sq/1572-rf-added-deleted-pages-and-change-findby
=> RF | Added deleted Pages and change FindBy

src/test/java/school/redrover/model/ConfigurePage.java, src/test/java/school/redrover/model/FreestyleProjectPage.java, src/test/java/school/redrover/model/JobPage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/NewViewFolderPage.java, src/test/java/school/redrover/model/ViewPage.java, src/test/java/school/redrover/model/base/BasePage.java
https://trello.com/c/yPRmv1iH/1575-rf-refactor-added-deleted-pages-and-change-findby
=> RF Refactor Added deleted Pages and change FindBy

src/test/java/school/redrover/PipelineTest.java
removing unused code
https://trello.com/c/Ktehg1Lt
=> RF 00.02 | New Item > Create Pipeline Project with the same name 

src/test/java/school/redrover/ConfigureGlobalSecurityTest.java, src/test/java/school/redrover/model/ConfigureGlobalSecurityPage.java, src/test/java/school/redrover/model/MainPage.java
[RF] - https://trello.com/c/3oBmCjdl/1584-rf-1801-configure-global-security-testchecknumberoftitles-to-pom
1. create ConfigureGlobalSecurityPage
2. refactor testCheckNumberOfTitles
=> RF 18.01 Configure Global Security | testCheckNumberOfTitles() to POM

src/test/java/school/redrover/ConfigureGlobalSecurityTest.java
[RF] - https://trello.com/c/3YYmQ7e6/1586-rf-1801-configure-global-security-testchecknumberofhelpbutton-to-pom
refactoring of testCheckNumberOfHelpButton to POM
=> RF 18.01 Configure Global Security | testCheckNumberOfHelpButton() to POM

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/NewJobPage.java
=> RF | Freestyle Project | testOKButtonIsDisabledWhenEmptyName()  to POM

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectConfigPage.java
=> RF 01.05 | Freestyle > EditDescriptionTest > RF to POM + add methods

src/test/java/school/redrover/DashboardTest.java, src/test/java/school/redrover/model/ConfigureGlobalSecurityPage.java, src/test/java/school/redrover/model/FreestyleProjectConfigPage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/runner/TestUtils.java
https://trello.com/c/ogg1rgQn 
RF of DashboardTest
=>  RF DashboardTest | Test Menu Is Shown When Clicking Button Near Project Name

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java, src/test/java/school/redrover/model/PipelinePage.java
=> AT 02.04 add set pipeline display name test

src/test/java/school/redrover/FooterJenkinsVersionTest.java, src/test/java/school/redrover/model/ManageJenkinsPage.java
https://trello.com/c/J9Fk7sjU
Refactoring testVerifyJenkinsVersionOnManageJenkinsPage
and rename method in ManageJenkinsPage POM
from getVersionJenkinsFromFooter
to isVersionJenkinsFromFooterCorrect
=> RF 13.01 | Footer > Verify Jenkins version on Manage Jenkins page use POM

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/NewJobPage.java
=> RF-testCreateProjectWithWrongName

src/test/java/school/redrover/ManageJenkinsTest.java
=> RF | delete empty class MultibranchPipeline3Test and extra blank line

src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/model/ViewPage.java
added testCreateMultiPipeline()
Added method clickMultiBranchPipeline()
https://trello.com/c/x5584d1u
=> AT 00.05 | New Item > Create Multibranch Pipeline with using new item button

src/test/java/school/redrover/DashboardBreadcrumbsTest.java, src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/CreateNodePage.java, src/test/java/school/redrover/model/ErrorNodePage.java, src/test/java/school/redrover/model/ManageJenkinsPage.java, src/test/java/school/redrover/model/ManageNodesPage.java, src/test/java/school/redrover/model/NewNodePage.java
=> RF | refactor testTextErrorWhenCreateNewNodeWithEmptyName() to POModel

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/ProfileTest.java, src/test/java/school/redrover/model/NewJobPage.java
=> RF 00.00 | PipelineTest > testCreateDuplicatePipelineProject

src/test/java/school/redrover/BreadcrumbTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/ManageJenkinsPage.java
=> refactor BreadcrumbTest testNavigateToManageJenkinsSection

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF 00.00 | PipelineTest > testCreatePipelineWithDescription

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF 00.00 | PipelineTest > testEditPipelineDescription

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java
=> RF 02.04 fix test problem

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/MultiConfigurationProjectConfigPage.java, src/test/java/school/redrover/model/MultiConfigurationProjectPage.java
AT - https://trello.com/c/9B2q3yPq
Add: new testConfigureOldBuildForMultiConfigurationProject() 
Add: 4 methods on MultiConfigurationProjectConfigPage
=> AT 03.05 | Multi-configuration project > Configure old build

pom.xml, src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/MyViewsTest.java, src/test/java/school/redrover/NewItemTest.java, src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/ManagePage.java
=> RF | Delete 2 dependencies from pom.xml

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF 00.00 | PipelineTest > testPipelineBuildNow

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/ErrorNodePage.java
=> RF 00.03| New Item > Multi Configuration project> Create Multi Configuration project with equal name>POM

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF | PipelineTest>testAddingDescriptionToPipeline

src/test/java/school/redrover/runner/TestUtils.java
https://trello.com/c/n4lgnT3X/1614-rf-pom-refactoring-testutils
=> RF | POM > Refactoring TestUtils

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/PipelineProject10Test.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/ConfigurePage.java, src/test/java/school/redrover/model/PipelineConfigPage.java, src/test/java/school/redrover/model/ProjectPage.java
https://trello.com/c/KR20JZlj/1607-at-0211-pipeline-add-description-after-rewrite
=> AT 02.11 Add description after rewrite

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/ConsoleOutputPage.java, src/test/java/school/redrover/model/FreestyleProjectConfigPage.java, src/test/java/school/redrover/model/FreestyleProjectPage.java
https://trello.com/c/C7Bd1WCn/1602-rf-0103-freestyle-project-build-now-check-shell-executing
=> RF 01.03 | Freestyle project > Build now -> Check shell executing

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF 00.00 | Pipelinetest > testPipelineConsoleOutputSuccess

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/ManageJenkinsPage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
https://trello.com/c/ksN4jfvB/1625-rf-1703-page-header-notification-and-security-icons-to-receive-alerts-from-jenkins
=> RF 17.03|Update testNotificationAndSecurityIcon to new POM design

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
https://trello.com/c/PMWAHssZ
Split into two tests testAppearanceOfPopUpMenusWhenClickingOnIcons >
a. testAppearanceOfPopUpMenuWhenClickingOnNotificationIcon
b. testAppearanceOfPopUpMenuWhenClickingOnAdminIcon
Moving methods >
a. isPopUpNotificationScreenDisplayed
b. isPopUpAdminScreenDisplayed
from MainPage to MainHeaderComponent
=> RF 17.03 | Page-header > Notification and Security icons > Appearance of pop up menu when clicking on icons use POM

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/PipelineConfigPage.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF 00.00 | Pipeline > testPipelineBuildingAfterChangesInCode

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectConfigPage.java
[RF](https://trello.com/c/u7qDLiGI/1636-rf-0000-item-sub-item)
=> RF_POM_FreestyleJobTest

src/test/java/school/redrover/PipelineTest.java
[RF 00.02 | New Item > Create Pipeline Project > testSetDescription](https://trello.com/c/CWTQMiZc/1645-rf-0002-new-item-create-pipeline-project-testsetdescription)
=> RF 00.02 | New Item > Create Pipeline Project > testSetDescription

src/test/java/school/redrover/ConfigureGlobalSecurityTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/ConfigureGlobalSecurityPage.java
https://trello.com/c/Bl5TIXjj/1640-at-1801-configure-global-security-%D1%81hange-settings-and-save-them
=> AT 18.01 | Configure Global Security> Сhange settings and save them

src/test/java/school/redrover/PipelineTest.java
=> AT 02.04 add boolean parameter without description test

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/nTV5ULKf
Rewrite the testReturnToTheDashboardPageAfterCreatingTheItem using POM
=> RF 17.01 | Page header > Logo > Return to the dashboard page after creating the Item use POM

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/ErrorNodePage.java
=> RF 00.03| New Item > Multi Configuration project> Create Multi Configuration project with space instead name

src/test/java/school/redrover/model/MovePage.java, src/test/java/school/redrover/model/RenamePage.java
=> RF | MovePage, RenamePage >generics refactoring

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProjectTest > testVisibleProjectNameAndDescriptionFromViewPage

src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/model/ViewPage.java, src/test/java/school/redrover/runner/TestUtils.java
refactoring testCreateNewViewWithJobFilters and moving methods clickBreadcrumbLinkItem(), createFreestyleProjectInsideFolderAndView()
RF - https://trello.com/c/xOf3T7kS/1659-rf-1101-views-new-view-create-new-view-create-new-view-with-job-filters
=> RF 11.01 | Views > New View > Create New View > Create New View with Job filters

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/MovePipelineToFolderTest.java, src/test/java/school/redrover/model/FolderPage.java
https://trello.com/c/TvcNmskd
Changing return type of method:
WebElement → String
and related tests:
testMoveFolderToFolder()
testCreateOrganizationFolderInFolder()
testMoveMultibranchPipelineToFolderByDrop()
testMoveFolderToFolderFromSideMenu()
testMovePipelineToFolder()
=> RF FolderPage > Refactoring getNestedFolder() and related tests

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/MultibranchPipelinePage.java
added methods: MainPage - clickMultibranchProjectName; MultibranchPipelinePage - clickMoveOnSideMenu; MultibranchPipelinePage - clickDashboard
https://trello.com/c/NaevwO91
=> RF 04.15 | POM Folder > Move Multibranch Pipeline to Folder from side menu

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/HlscwHrz
Refactoring test to POM
Delete two useless tests
=> RF 00.00 | Pipeline > testSetDescriptionPipeline

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
https://trello.com/c/WbhBQxnF/1675-rf-1704-page-header
deleted DataProvider
Refactoring: testOpenBuildsTabFromDropdownMenu(), testConfigureTabFromDropdownMenu(), testMyViewsTabFromDropdownMenu(), testCredentialsTabFromDropdownMenu() 
Moved methods from MainPage to MainHeaderComponent
=> RF 17.04 | Page-header | Refactoring tests |

src/test/java/school/redrover/BuildHistoryPageTest.java, src/test/java/school/redrover/model/ConsoleOutputPage.java, src/test/java/school/redrover/model/MainPage.java
=> AT 08.02 | Build History> History of one build > View user that started the build

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/MultiConfigurationProjectConfigPage.java, src/test/java/school/redrover/model/MultiConfigurationProjectPage.java, src/test/java/school/redrover/model/ProjectPage.java
=> RF 03.02 | Multi-Configuration >Enable \ Disable project

src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/ConfigureGlobalSecurityPage.java, src/test/java/school/redrover/model/ConfigureUserPage.java, src/test/java/school/redrover/model/ConsoleOutputPage.java, src/test/java/school/redrover/model/CreateItemErrorPage.java, src/test/java/school/redrover/model/CreateNodePage.java, src/test/java/school/redrover/model/CreateUserPage.java, src/test/java/school/redrover/model/ErrorNodePage.java, src/test/java/school/redrover/model/JobPage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/ManageJenkinsPage.java, src/test/java/school/redrover/model/ManageNodesPage.java, src/test/java/school/redrover/model/ManagePage.java, src/test/java/school/redrover/model/ManageUsersPage.java, src/test/java/school/redrover/model/MyViewsPage.java, src/test/java/school/redrover/model/NewNodePage.java, src/test/java/school/redrover/model/NewViewFolderPage.java, src/test/java/school/redrover/model/NewViewPage.java, src/test/java/school/redrover/model/RestApiPage.java, src/test/java/school/redrover/model/StatusUserPage.java, src/test/java/school/redrover/model/ViewConfigPage.java, src/test/java/school/redrover/model/ViewFolderPage.java, src/test/java/school/redrover/model/ViewPage.java
=> RF | Refactor the classes of pages adding inheritance from BaseMainHeaderPage instead of MainPage

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/PQ9mkLUm/1693-rf-0414-folder-move-multiconfiguration-project-to-folder-from-side-menu
=> RF 04.14 | Folder > Move Multiconfiguration project to Folder From Side Menu

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/ConfigureUserPage.java, src/test/java/school/redrover/model/CreateUserPage.java, src/test/java/school/redrover/model/ManagePage.java, src/test/java/school/redrover/model/ManageUsersPage.java, src/test/java/school/redrover/model/StatusUserPage.java
Refactoring and combaining <Manage Users> tests -  https://trello.com/c/H4nv9u70
following tests are moved from ManageJenkinsTest to UserTest class: 
testCreateNewUser()
testCreateNewUserWithInvalidEmail()
testAddDescriptionToUserOnTheUserProfilePage()
testDeleteUser() -> testDeleteUserByDeleteButton()
and related methods moved to ManageUserPage, CreateUserPage, ConfigureUserPage:
.fillUserDetails(), 
.fillUserDetailsWithInvalidEmail() 
.submit() -> clickYesButton()
.assertInvalidEmailError() -> getInvalidEmailError()
.findUserCreated() -> removed as duplicate of isUserExist()
Existing tests renamed in class UsersTest:
testEditEmailByDropDown() -> testEditEmailOnTheUserProfilePageByDropDown()
testAddDescriptionToUser() -> testAddDescriptionToUserOnUserStatusPage() …
=> RF | Manage Users > UsersTest and ManageJenkinsTest classes refactoring

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java
=> RF 00.00 | Pipeline > testDiscardOldBuildsPipeline

src/test/java/school/redrover/HeaderTest.java
=> RF 17.03 | Page-header > Notification and Security icons > Split and update test

src/test/java/school/redrover/MultiConfigurationProjectTest.java
https://trello.com/c/Qz20WzNU/1705-rf-multiconfiguration-refactoring-to-pom
=> RF 03.03| MultiConfiguration > refactoring to POM

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/NewItemTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/FolderPage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/NewJobPage.java
=> RF 04.09| Folder > Create Folder in Folder

src/test/java/school/redrover/MultiConfigurationProjectTest.java
https://trello.com/c/Y4W8I6qy/1708-rf-0307-multiconfiguration-rename-project-refactoring-to-pom
=> RF 03.07 | MultiConfiguration> Rename project> Refactoring to POM

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java
=> RF | New Item > PipelineConfigPage > getDefinitionFieldText()

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/BaseJobPage.java, src/test/java/school/redrover/model/FolderPage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/MultiConfigurationProjectConfigPage.java, src/test/java/school/redrover/model/MultiConfigurationProjectPage.java, src/test/java/school/redrover/model/ProjectPage.java
=> RF 00.00  project page changed to abstract

src/test/java/school/redrover/MultiConfigurationProjectTest.java
=> ERR | MultiConfigurationProjectTest > testAddDescriptionInMultiConfigurationProject

src/test/java/school/redrover/RestAPITest.java
https://trello.com/c/LLVwB3hf/1712-rf-0000-restapilinktest
=> RF 13.02 | Footer > RestApiLinkTest

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/ConsoleOutputPage.java, src/test/java/school/redrover/model/PipelinePage.java, src/test/java/school/redrover/model/TimelinePage.java
=> RF | Pipeline > testBuildPipeline

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/model/BuildHistoryPage.java, src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/PipelineConfigPage.java
add new methods in existing classes
https://trello.com/c/bOv8my1M
=> RF 02.03 | POM Pipeline > Configure Page > Pipeline Status check

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/JobPage.java
https://trello.com/c/3OyFFSDz/1721-rf-multiconfiguration-project
=> RF | MultiConfiguration Project > refactoring old test and delete variable 

src/test/java/school/redrover/PipelineTest.java
=> RF | PipelineTest> testPipelineNameAllowedChar

src/test/java/school/redrover/MultiConfigurationProjectTest.java
deleted Ignore, maked renameTest from project page to Rename from dashboard
=> RF | MultiConfigurationProjectTest | testRenameFromDashboard > refactor

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/model/ConsoleOutputPage.java
=> AT 08.02 | Build History> History of one build > View build status

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/RenamePage.java
RF - https://trello.com/c/YXKXcw2a/1729-rf-multiconfigurationprojecttest-verifyprojectnamerenamewithunsafesymbolstest
=> Rf multi configuration project test verify project name rename with unsafe symbols test

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/CreateNodePage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/ManageNodesPage.java
=> ERR |ManageJenkinsTest > testNameNewNodeOnCreatePage()

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/NewJobPage.java
=> RF POM > testCreatePipelineWithSpaceInsteadOfName

src/test/java/school/redrover/BuildPageTest.java
https://trello.com/c/Vp7N4HMb/1740-rf-buildpagetest-deleted-variable-with-used-0ne-time
=> RF | BuildPageTest > deleted variable with used 0ne time

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/NBth4IsU/1730-rf-freestyleprojecttest-createfreestyleproject
=> refactor POM

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/NBth4IsU/1730-rf-freestyleprojecttest-refactor-pom
=> added POM tests

src/test/java/school/redrover/ManagePluginsTest.java, src/test/java/school/redrover/model/ManageJenkinsPage.java, src/test/java/school/redrover/model/ManagePluginsPage.java
=> AT 09.04 | Manage Jenkins > Manage Plugins > Verify that there are 4 tasks on the leftside panel of the page

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/runner/TestUtils.java
=> RF | Pipeline> testSortingPipelineProjectAplhabetically

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/FolderPage.java, src/test/java/school/redrover/model/FreestyleProjectPage.java
RF: https://trello.com/c/yMwDh6AC
=> RF POM 04.12 | Folder > Move Freestyle Project to Folder by side menu

src/test/java/school/redrover/DashboardTest.java, src/test/java/school/redrover/model/PluginsPage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
=> RF 12.01 |  POM > Select Plugins from the drop-down menu from People Page

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/OrganizationFolderConfigPage.java, src/test/java/school/redrover/model/OrganizationFolderPage.java
https://trello.com/c/ZxS6CEGs/1750-at-0601-organization-folder-create-disable-organization-folder
=> AT 06.01 | Organization Folder > Create Disable Organization Folder

src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/model/MainPage.java
=> AT 00.05 | Multibranch Pipeline > Find the created on the dashboard

src/test/java/school/redrover/model/ChangesPage.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF | ChangesPage

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/OrganizationFolderConfigPage.java, src/test/java/school/redrover/model/OrganizationFolderPage.java
https://trello.com/c/SBrKZ9je/1755-at-0604-organization-folder-create-organization-folder-with-description
=> AT 06.04 | Organization Folder > Create Organization Folder with Description

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/Ehph9Dc9/638-at-0205-pipeline-delete-pipeline-cancel-deleting-the-pipeline-project
=> AT 02.05 | Pipeline > Delete Pipeline > Cancel deleting the pipeline project

src/test/java/school/redrover/PipelineTest.java
=> AT 02.01 | Pipeline > View pipeline page > Open created Pipeline by mouse click

src/test/java/school/redrover/runner/TestUtils.java
=> RF 00.00 TestUtils - remove unused methods

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectPage.java
https://trello.com/c/R6j2JR1m/1725-rf-0000-freestyleprojecttest-testdeletefreestyleproject
=> PR FreestyleProject > testDeleteFreestyleProject

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/MainPage.java
=> RF 03.07 | Multi-Configuration project > Rename Multi-Configuration project from drop-down menu>POM

src/test/java/school/redrover/OrganizationFolderTest.java
=> RF add depenedsOnMethods to OrgFolderTests

src/test/java/school/redrover/DashboardTest.java, src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/FolderConfigPage.java, src/test/java/school/redrover/model/FreestyleProjectConfigPage.java, src/test/java/school/redrover/model/MultiConfigurationProjectConfigPage.java, src/test/java/school/redrover/model/MultibranchPipelineConfigPage.java, src/test/java/school/redrover/model/NewViewPage.java, src/test/java/school/redrover/model/OrganizationFolderConfigPage.java, src/test/java/school/redrover/model/ViewConfigPage.java, src/test/java/school/redrover/model/base/BaseConfigPage.java, src/test/java/school/redrover/model/base/BaseFoldersConfigPage.java, src/test/java/school/redrover/model/base/BaseProjectsConfigPage.java, src/test/java/school/redrover/runner/TestUtils.java
=> RF | Create BaseFoldersConfigPage, BaseProjectsConfigPage

src/test/java/school/redrover/MyViewsTest.java
https://trello.com/c/rhgYPIQG/1783-rf-1101-my-views-rf-tests-to-pom
=> RF 11.01 | My Views >RF  tests to POM

src/test/java/school/redrover/MultiConfigurationProjectTest.java
https://trello.com/c/1zHElFIt/1787-at-0303-multiconfigurationtest-create-multiconfiguration-project-and-check-this-on-project-page
=> AT 03.03 | MultiConfigurationTest > Create MultiConfiguration Project 

src/test/java/school/redrover/MultiConfigurationProjectTest.java
https://trello.com/c/7rSQsU9j/1788-rf-multiconfiguration-project-delete-method-from-testutils
=> RF | MultiConfiguration Project > delete method From TestUtils

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectPage.java, src/test/java/school/redrover/model/MainPage.java
=> RF - FreestyleProjectPage - changing Delete method to redirect to proper page

src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/model/MultibranchPipelineConfigPage.java, src/test/java/school/redrover/model/MultibranchPipelinePage.java
https://trello.com/c/ZYbC9YqR/1790-at-0504-multibranch-pipeline-configuration-multibranch-pipeline-testdisablemultibranchpipeline
=> AT 05.04 | Multibranch pipeline > Configuration Multibranch pipeline > testDisableMultibranchPipeline()

src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/model/MultibranchPipelinePage.java
=> RF  | MultibranchPipelineTest > refactor tests so that the assert would be more accurate

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF - FreestyleProjectTest - convert testDeleteFreestyleProject to POM

src/test/java/school/redrover/ManagePluginsTest.java, src/test/java/school/redrover/model/AdvancedSettingsPage.java, src/test/java/school/redrover/model/ManagePluginsPage.java, src/test/java/school/redrover/model/PluginsPage.java
=> AT 09.04 | POM Manage Jenkins > Manage Plugins > Check explanatory info for Server in Advance Settings page

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/OrganizationFolderPage.java
https://trello.com/c/Uo4Qd2qJ/1806-at-0303-organization-folder-change-status-to-disable
=> AT 06.01 | Organization Folder > Configuration Page> change status To Disable

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/LoginPage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
https://trello.com/c/yoeJ6eWn/1810-at-150601-users-user-can-login-to-jenkins-with-created-account-and-create-project
=> User can login to Jenkins with created account and create project

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/TcveY35f/1816-rf-freestyleprojecttest-testrenamingprojectfromthedashboard-to-pom
=> rf testRenameFreestyleProjectUsingDropDownMenu to POM

src/test/java/school/redrover/MultiConfigurationProjectTest.java
https://trello.com/c/LcFnSQu0/1819-rf-multiconfigurationprojecttest-testcreatemulticonfigurationprojectwithspecialsymbols-to-pom
=> rf testCreateMultiConfigurationProjectWithSpecialSymbols to POM

src/test/java/school/redrover/UsersTest.java
https://trello.com/c/W4BfV1iY/1823-at-150603-users-inputting-an-incorrect-password
=> Inputting an incorrect password

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/runner/TestUtils.java
=> 18.01 | Nodes > Manage Nodes and Clouds > Create new agent node using valid name

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/MultiConfigurationProjectPage.java, src/test/java/school/redrover/model/base/BaseJobPage.java, src/test/java/school/redrover/model/base/BaseProjectPage.java
=> RF - MultiConfigurationProjectPage - converting to extend BaseProjectPage

src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/model/FreestyleProjectPage.java, src/test/java/school/redrover/model/ViewConfigPage.java, src/test/java/school/redrover/model/ViewPage.java
[TC](https://trello.com/c/ZlMlN41d/1767-tc-1103-views-new-view-edit-viewadd-view-description-preview)
[AT](https://trello.com/c/F4ZpabOI/1768-at-1103-views-new-view-edit-viewadd-view-description-preview)
=> AT_11.03AddViewDescriptionPreview

src/test/java/school/redrover/NewViewTest.java
[RF](https://trello.com/c/wzSHA0Ch/1828-rf-0000-item-sub-item-title)
=> RF_11.03AddViewDescriptionPreview

src/test/java/school/redrover/BuildPageTest.java
https://trello.com/c/x5ATv64J/1834-rf-buildpagetest-delete-testadddescriptionforbuild1-as-a-duplicate
=> Delete testAddDescriptionForBuild1 as a duplicate

src/test/java/school/redrover/MyViewsTest.java
https://trello.com/c/GEKIEyIr/1835-rf-views-myview-delete-constant-witch-used-one-time
=> RF Views > MyView > delete constant witch used one time

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java, src/test/java/school/redrover/model/base/BaseConfigPage.java
https://trello.com/c/WvA5xZ9y/1831-rf-baseconfigpage-add-preview-methids-to-baseconfigpage-delete-duplicates-on-other-pages
=> RF  | BaseConfigPage > add preview methods to BaseConfigPage, delete duplicates on other pages

src/test/java/school/redrover/NewViewTest.java
https://trello.com/c/524DwNea/1836-rf-views-newview-delete-constants
=> RF Views| NewView >Delete constants

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/ErrorNodePage.java
=> RF 00.03| New Item > Multi Configuration project> Create Multi Configuration project with equal name>deletd from Ignore

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java
https://trello.com/c/AHg0IAC5/1838-at-0204-pipeline-adding-a-project-on-github-to-the-pipeline-project
=> AT 02.04 | Pipeline > adding a project on github to the Pipeline project

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/CreateUserPage.java, src/test/java/school/redrover/model/UserConfigPage.java
AT - https://trello.com/c/LLFVyteU
=> At 5.01 | Users > Create users > Error when creating dublicated user

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/AUyxi0YS/1843-rf-0000-item-sub-item-title
=> Test method clickJobName

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/dcgQPs60/1850-rf-0000-item-sub-item-at-title
=> RF | MainPage > Implements clickJobName

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/model/BuildHistoryPage.java
=> AT 08.01 | Build History> View the build history > Test that the build history of two different types projects is seen on the Build History Page

src/test/java/school/redrover/FooterTest.java, src/test/java/school/redrover/model/JenkinsVersionPage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
=> RF | FooterTest

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelineConfigPage.java
=> RF | Pipeline > testDiscardOldBuildsIsChecked0Days

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectConfigPage.java, src/test/java/school/redrover/model/FreestyleProjectPage.java, src/test/java/school/redrover/model/PipelineConfigPage.java
https://trello.com/c/PlXPZVjY/1852-at-0104-freestyle-project-adding-a-project-on-github-to-the-freestyle-project
=> AT 01.04 | Freestyle Project > adding a project on GitHub to the Freestyle project

src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/ViewDeletePage.java, src/test/java/school/redrover/model/ViewPage.java
RF: https://trello.com/c/rcLw8QQY
=> RF POM 11.04 | Views > Delete view

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/PipelinePage.java, src/test/java/school/redrover/model/base/BaseJobPage.java
https://trello.com/c/5bkTnetB/1839-rf-pipelinepage
=> RF PipelinePage extends BaseProjectPage, remove duplicate methods

src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/model/ViewConfigPage.java, src/test/java/school/redrover/model/ViewPage.java
[RF 11.03 |Views > New View >Edit View>Help for feature: Description](https://trello.com/c/WAjeWIQh/1809-rf-1103-views-new-view-edit-viewhelp-for-feature-description)
=> Add refactor of test in POM

src/test/java/school/redrover/OrganizationFolderTest.java
=> AT 06.01 | Organization Folder > Rename Negative

src/test/java/school/redrover/DashboardTest.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
=> RF | DashboardTest > testDashboardDropdownMenu

src/test/java/school/redrover/MyViewsTest.java
https://trello.com/c/PnoyKg9s/1872-rf-1101-my-views-rf-test
=> RF 11.01 | My Views >RF test

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectConfigPage.java
[RF](https://trello.com/c/bqEfymUa/1864-rf-0000-freestyle-job-test-changing-expectations)
=> RF_FreestyleJobTestChangingExpectations

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/NewNodePage.java
=> AT 18.01 | Nodes > Manage Nodes and Clouds > Create a new agent node by copying an existing node

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/EVqPzhTY/1882-at-0104-freestyle-project-configure-add-description
=> AT 01.04 | Freestyle Project > Configure > Add description

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectPage.java
=> AT 01.01 | Freestyle project>View project page>Delete a project without confirmation

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/hVILRtcl/1886-rf-freestyleprojecttest-refactor-class-refactor-pom-dependency
=> RF FreestyleProjectTest > refactor class, refactor POM, dependency

src/test/java/school/redrover/DashboardTest.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
=> RF | MainHeaderComponent methods

src/test/java/school/redrover/PipelineTest.java
=> Add changes to testDeletePipelineLeftMenu, RF Assert

src/test/java/school/redrover/FolderTest.java
=> RF | FolderTest> create createdJobInFolderIsDisplayed

src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/model/MultibranchPipelinePage.java, src/test/java/school/redrover/model/base/BaseConfigPage.java
https://trello.com/c/H40E6Px1/1899-rf-multibranchpipelinetest-rf-asserts-in-tests
=> RF asserts in MultiBranch tests

src/test/java/school/redrover/MultiConfigurationProjectTest.java
…
https://trello.com/c/I8Rnk4mI
=> RF 00.03| New Item > Multi Configuration project> Create Multi Confuration project with equal name>deletd from Ignore

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/PeoplePage.java
[RF] - https://trello.com/c/AIcHujE3
=> RF | POM > UsersTest > testSortArrowModeChangesAfterClickingSortHeaderButton()

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/PipelinePage.java
=> RF | Pipeline > testDiscardOldBuildsIsCheckedWithValidParams

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java
=> RF  Multi Configuration projectTest

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/ManageJenkinsPage.java
=> AT 09.09 | Manage Jenkins > Access search settings field using shortcutKey

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java
https://trello.com/c/xZx7PPx2/1902-at-0104-freestyle-project-configure-set-parameters-to-discard-old-builds
=> AT 01.04 | Freestyle Project > Configure > Set parameters to discard old builds

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/CreateItemErrorPage.java, src/test/java/school/redrover/model/OrganizationFolderPage.java
[AT] - https://trello.com/c/trat0ok9
=> AT 06.03 | Organization folder > Delete Organization Folder

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/FolderPage.java
refactor FolderPAge and create AT 04.16 | Folder > Move Organization Folder to Folder
=> AT 04.16 | Folder > Move Organization Folder to Folder

src/test/java/school/redrover/HeaderTest.java
https://trello.com/c/PLUzCwcM/1923-rf-1701-header-refactoring-old-test-to-pom
=> RF 17.01 | Header > refactoring old test To POM 

src/test/java/school/redrover/MyViewsTest.java, src/test/java/school/redrover/model/MyViewsPage.java
=> RF | MyViewsTest

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/ErrorNodePage.java, src/test/java/school/redrover/model/NewNodePage.java
=> AT 18.01 | Nodes > Manage Nodes and Clouds > Create a new agent node by copying a non-existing node

src/test/java/school/redrover/DashboardTest.java
https://trello.com/c/PS6rFCDi/1928-rf-1202-dashboard-refactoring-to-pom
=> RF 12.02| Dashboard > refactoring To POM

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/MainPage.java
=> RF | Pipeline > testDeletePipelineDropDownMenu

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/LIyUOYtM
- change method how to make the step of test from .getProjectNameMainPage(name) to .verifyJobIsPresent(name)
- correct the Assertion
=> RF | FreestyleProjectTest > testDeleteProjectWithoutConfirmation

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/SearchTest.java, src/test/java/school/redrover/model/UserConfigPage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
https://trello.com/c/XMaSI96N/1924-rf-searchtest-to-pom
=> RF | SearchTest to POM

src/test/java/school/redrover/ConfigureGlobalSecurityTest.java, src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/ManagePluginsTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/ConfigureGlobalSecurityPage.java, src/test/java/school/redrover/model/CreateUserPage.java, src/test/java/school/redrover/model/MainPage.java
=> RF | ConfigureGlobalSecurityTest> testCheckTitleTexts > to POM

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/NewItemTest.java
https://trello.com/c/UuwUIsYO/1932-rf-0002-new-item-create-new-project-with-invalid-name
refactor  testCreateFreestyleProjectWithInvalidName 
transfer to the appropriate class NewItemTest and deleted same tests
=> RF 00.00| New Item > Create New Project With Invalid Name

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/CreateItemErrorPage.java
=> ERR testCreateMultiConfigurationProjectWithEqualName

src/test/java/school/redrover/MultiConfigurationProjectTest.java
https://trello.com/c/mdnSsKWK/1933-rf-03-multiconfiguration-project-refactoring-class-delete-duplicate-tests
удаление дубликатов тестов
=> RF 03| MultiConfiguration Project> refactoring class > delete duplicate Tests

src/test/java/school/redrover/NewItemTest.java
https://trello.com/c/soBs5j4Z/1934-rf-0000-new-item-create-new-item-with-empty-name
refactor  testCreateNewItemWithEmptyName and deleted same test
=> RF 00.00| New Item> Create New Item With Empty Name

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/NewJobPage.java, src/test/java/school/redrover/runner/TestUtils.java
=> RF | refactoring selectJobType method > refactoring class enum JobType

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/ConfigureSystemPage.java, src/test/java/school/redrover/model/ManageJenkinsPage.java
https://trello.com/c/cSrgdYVW/1937-rf-0902-manage-jenkins-search-settings
=> RF | POM | 09.02 | Manage Jenkins > Search settings > Search for Configure System by entering "c"

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProjectTest > testCreateFreestyleProject

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/LoginPage.java, src/test/java/school/redrover/model/NewJobPage.java, src/test/java/school/redrover/model/PeoplePage.java
=> RF UsersTest > CreateUser

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/MyViewsTest.java, src/test/java/school/redrover/NewViewTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/runner/TestUtils.java
=> RF | create method createJob in TestUtils class

src/test/java/school/redrover/NewItemTest.java, src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/DXebjiqi/1943-at-0001-new-item-freestyle-project-create-freestyle-project-from-other-existing
add enterItemNameToPlaceHolder to NewJobPage for creating new project from other exiting
add testCreateNewItemFromOtherExisting
=> AT 00.01 | New Item > Freestyle Project > Create Freestyle Project From Other Existing

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java
https://trello.com/c/xnTahnd9/1944-tc-0104-freestyle-project-configure-make-a-freestyleproject-parametrized-and-set-the-of-parameters-for-it-boolean-parameter
=> AT 01.04 | Freestyle Project > Configure > make a FreestyleProject parametrized and set the of parameters for it > Boolean Parameter

src/test/java/school/redrover/PipelineTest.java
=> RF | PipelineTest

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/OrganizationFolderPage.java
https://trello.com/c/p1UzhkTk/1952-rf-1703-header-refactoring-old-test-to-pom
=> RF 17.03 | Header > refactoring old test To POM

src/test/java/school/redrover/MyViewsTest.java
https://trello.com/c/hpsQiN0b/1888-rf-myviewstest-refactor-class-refactor-pom-dependency
=> RF MyViewsTest > refactor class, refactor POM, dependency

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/base/BaseProjectPage.java
=> RF | MultiConfigurationProjectTest > testDisable

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/hVILRtcl/1886-rf-freestyleprojecttest-refactor-class-refactor-pom-dependsonmethods
=> refactor testDisableProject

src/test/java/school/redrover/MyViewsTest.java, src/test/java/school/redrover/model/MyViewsPage.java
https://trello.com/c/DfqNxk3a/1955-at-1101-views-create-newviews-from-myviewspage
=> AT 11.01 | Views > Create NewViews From MyViewsPage

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/FolderPage.java
=> RF | Item> class FolderTest > testCreateJobsInFolder

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java
Add new testBuildStepsOptions()
=> AT 01.04 | Freestyle Project > Configure > test Build Steps Options

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/FreestyleProjectPage.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java
https://trello.com/c/vlIFNZa3/1972-rf-freestyleprojecttest-test-dependency-chain-fix
=> RF FreestyleProjectTest > Test dependency chain fix

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
https://trello.com/c/Cz0q3vmH/1968-rf-1703-header-rf-old-test-to-pom
=> RF 17.03 Header > rf old test to POM

src/test/java/school/redrover/model/PipelinePage.java, src/test/java/school/redrover/model/base/BaseModel.java
=> RF | PipelinePage add FindBy and PageFactory

src/test/java/school/redrover/model/LoginPage.java
=> RF LoginPage withFindBy

src/test/java/school/redrover/BreadcrumbTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/Jobs/OrganizationFolderPage.java
https://trello.com/c/bTGbJBg6/1978-rf-organizationfolderpage-add-fyby
=> RF  | OrganizationFolderPage > Add FindBy

src/test/java/school/redrover/model/NewNodePage.java
=> RF | NewNodePage with FindBy

src/test/java/school/redrover/model/PluginsPage.java
=> RF PlaginsPage add FindBy

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/BuildHistoryPage.java, src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/4vQ3AqVs
Create @Test testCreateFolderGoingFromBuildHistoryPage()
=> AT 04.00| Folder > Create FolderGoing From Build History Page

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/AdminPage.java, src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/MS4dzejn/1989-at-1704-page-header-user-profile-icon-users-profile-icon
=> AT 17.04 | Page-header > User Profile Icon > rf old test to POM

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/CreateUserPage.java, src/test/java/school/redrover/runner/TestUtils.java
RF - https://trello.com/c/Xamn2tVF
CreateUser() moved to testUtils 
the method just updated in tests of TestUser class
=> RF_09.01 > move: CreateUser() to testUtils 

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/JobsConfig/OrganizationFolderConfigPage.java
https://trello.com/c/JcGflFjk/1985-rf-organizationfolderconfigpage-added-findby-on-orgfolderconfig
=> RF | OrganizationFolderConfigPage > added FindBy on OrgFolderConfig

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/JobsConfig/PipelineConfigPage.java
=> RF | PipelineConfigPage add FindBy

src/test/java/school/redrover/model/CreateItemErrorPage.java
=> RF  CreateErrorItemPage add FindBy

src/test/java/school/redrover/model/Jobs/MultibranchPipelinePage.java
https://trello.com/c/euzyu4P4/1995-rf-multibranch-pipeline-page-added-findby
=> RF  | Multibranch Pipeline Page> Added FindBy

src/test/java/school/redrover/model/AdminPage.java
=> RF | AdminPage > add FindBy

src/test/java/school/redrover/ConfigureGlobalSecurityTest.java, src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/ConfigureGlobalSecurityPage.java
[RF] - https://trello.com/c/vi2KJ110/1993-rf-configureglobalsecuritypage-add-findby
added FindBy to ConfigureGlobalSecurityPage
=> RF | ConfigureGlobalSecurityPage > Add FindBy

src/test/java/school/redrover/model/ChangesPage.java
=> RF | ChangesPage > add FindBy

src/test/java/school/redrover/model/ConfigureSystemPage.java
=> RF | ConfigureSystemPage > add FindBy

src/test/java/school/redrover/model/ConsoleOutputPage.java
=> RF | ConsoleOutputPage > add FindBy

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/base/BaseJobPage.java, src/test/java/school/redrover/model/jobs/FolderPage.java, src/test/java/school/redrover/model/jobs/FreestyleProjectPage.java, src/test/java/school/redrover/model/jobs/MultibranchPipelinePage.java, src/test/java/school/redrover/model/jobs/PipelinePage.java
=> RF | delete methods from BaseJobPage in children BaseJobPage

src/test/java/school/redrover/MultiConfigurationProjectTest.java
=> RF | MultiConfigurationProjectTest |  delete and rename

src/test/java/school/redrover/model/EditBuildInformationPage.java
=> RF | EditBuildInformationPage > Add FindBy

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/ManageJenkinsPage.java, src/test/java/school/redrover/model/base/BaseJobPage.java
=> RF | ManageJenkinsPage > Add FindBy

src/test/java/school/redrover/model/JenkinsVersionPage.java
=> RF | JenkinsVersionPage > Add FindBy

src/test/java/school/redrover/model/CreateUserPage.java
=> RF CreateUserPage add FindBy

src/test/java/school/redrover/model/ManagePluginsPage.java
=> RF ManagePluginsPage_add_FindBy

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/ManageUsersPage.java, src/test/java/school/redrover/model/StatusUserPage.java, src/test/java/school/redrover/model/UserConfigPage.java
RF - ManageUserPage, UserConfigPage, StatusUserPage > add FindBy
=> RF |  ManageUserPage, UserConfigPage, StatusUserPage > add FindBy

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java, src/test/java/school/redrover/model/base/BaseProjectPage.java, src/test/java/school/redrover/model/jobs/FreestyleProjectPage.java
https://trello.com/c/u4nYwVCu/2013-at-0104-freestyle-project-configure-set-a-rate-limit-for-builds
=> AT 01.04 | Freestyle Project > Configure > Set a rate limit for builds

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/MultibranchPipelineTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/DeletePage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/ManageUsersPage.java, src/test/java/school/redrover/model/MyViewsPage.java, src/test/java/school/redrover/model/ViewPage.java, src/test/java/school/redrover/model/base/BaseJobPage.java, src/test/java/school/redrover/model/base/BaseOtherFoldersPage.java, src/test/java/school/redrover/model/jobs/FolderPage.java, src/test/java/school/redrover/model/jobs/MultibranchPipelinePage.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java, src/test/java/school/redrover/model/jobs/PipelinePage.java
=> RF | create BaseOtherFoldersPage

src/test/java/school/redrover/model/jobs/FreestyleProjectPage.java
=> RF 01.01 | Freestyle project > Add FindBy

src/test/java/school/redrover/BreadcrumbTest.java, src/test/java/school/redrover/model/component/MainBreadcrumbComponent.java
RF - https://trello.com/c/eACiTKC4/2022-rf-breadcrumbtest-testnavigatetomanagejenkinssubsection
=> RF | > BreadcrumbTest > testNavigateToManageJenkinsSubsection

src/test/java/school/redrover/UsersTest.java
https://trello.com/c/u5vqiobS/2026-rf-0000-user-refactoring-old-test-to-pom
=> RF 15.00 | User > refactoring old test to POM

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/NewJobPage.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
https://trello.com/c/prftrFk2/2027-at-0104-freestyle-project-configure-allow-to-execute-concurrent-builds
=> AT 01.04 | Freestyle Project > Configure > allow to execute concurrent builds

src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
=> RF FreestyleProjectConfigPage > Add FindBy

src/test/java/school/redrover/model/BuildPage.java
https://trello.com/c/rGHyQwRV/2028-rf-buildpage-added-findby
=> RF | BuildPage> added FindBy

src/test/java/school/redrover/ViewsTest.java, src/test/java/school/redrover/model/MyViewsPage.java
https://trello.com/c/dAM7nErY/2029-rf-myviewpage-add-findby
=> RF | MyViewPage > Add FindBy

src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/base/BaseJobPage.java, src/test/java/school/redrover/model/jobs/PipelinePage.java
=> RF | refactoring getProjectNameSubtitle method

src/test/java/school/redrover/model/DeletePage.java, src/test/java/school/redrover/model/NewViewPage.java
=> RF NewViewPage | DeletePage > add findBy

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java
https://trello.com/c/xdjU90Bk/2037-rf-baseconfigprojectpage-addition-finby
=> RF  | BaseConfigProjectPage > addition FinBy

src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/model/CreateItemErrorPage.java, src/test/java/school/redrover/model/NewJobPage.java
=> RF | MultiConfigurationProjectTest > Tests refactor

src/test/java/school/redrover/ViewsTest.java, src/test/java/school/redrover/model/ViewConfigPage.java, src/test/java/school/redrover/model/ViewPage.java
https://trello.com/c/VyTyPuaV/2024-rf-move-some-methods-from-viewpage-to-the-viewconfigpage
=> RF Move some methods from ViewPage to the ViewConfigPage

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/model/BuildHistoryPage.java, src/test/java/school/redrover/model/BuildPage.java
=> AT 08.04 | Build History > History of one build > Delete the build

src/test/java/school/redrover/model/ViewFolderPage.java
=> RF | ViewFolderPage > Add FindBy

src/test/java/school/redrover/model/ActiveViewPage.java, src/test/java/school/redrover/model/BuildHistoryPage.java
=> Add find by build history page

src/test/java/school/redrover/model/NewJobPage.java, src/test/java/school/redrover/model/RenamePage.java
=> RF NewJobPage | RenamePage > add findBy

src/test/java/school/redrover/UsersTest.java
https://trello.com/c/5YQ2Spv1/2042-rf-userstest-deleting-a-test-as-a-duplicate
=> RF | UsersTest >deleting a test as a duplicate

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/MainPage.java
Add dependsOnMethods in the UsersTest
=> RF 09.01 | Manage Jenkins > Manage Users > Create User

src/test/java/school/redrover/model/RestApiPage.java
=> RF | RestApiPage add FindBy

src/test/java/school/redrover/model/ViewConfigPage.java
=> RF ViewConfigPage > add findBy

src/test/java/school/redrover/model/ManageNodesPage.java
=> RF | ManageNodesPage > Add FindBy

src/test/java/school/redrover/UsersTest.java
=> ERR || > testCreateUserCheckInPeople()

src/test/java/school/redrover/model/MovePage.java
=> RF | MovePage > add FindBy

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/BuiltInNodePage.java, src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/jKBdbCDU/2048-rf-headertest-refactoring-old-test-to-pom
=> RF  | HeaderTest > refactoring old test to POM

src/test/java/school/redrover/model/NodePage.java
=> RF | NodePage > add FindBy

src/test/java/school/redrover/model/base/BaseConfigPage.java
=> RF | BaseConfigPage > add FindBy

src/test/java/school/redrover/model/CreateNodePage.java
https://trello.com/c/hML1ZxZw/2056-rf-createnodepage-add-findby
=> RF | CreateNodePage > Add FindBy

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/UserPage.java
https://trello.com/c/sbEh7TZT/2058-rf-usertest-refactoring-old-test-to-pom
=> RF  UserTest > refactoring old test to POM

src/test/java/school/redrover/model/PeoplePage.java
https://trello.com/c/eTu4NXw2/2063-rf-peoplepage-findby
=> added FindBy on PeoplePage

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
https://trello.com/c/4aet6dri/2064-at-0104-freestyle-project-configure-set-a-number-of-count-for-jenkins-to-check-out-from-the-scm-until-it-succeeds
=> AT 01.04 | Freestyle Project > Configure > set a number of count for Jenkins to check out from the SCM until it succeeds

src/test/java/school/redrover/model/NewViewFolderPage.java
https://trello.com/c/G8xdsXdV/2062-rf-newviewfolderpage-findby
=> added FindBy on NewViewFolderPage

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
https://trello.com/c/XMdn5nF1/2065-rf-headertest-refactoring-old-test-to-pom
=> RF HeaderTest > refactoring old test to POM

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/UserDeletePage.java, src/test/java/school/redrover/model/UserPage.java
=> RF | UserDeletePage, UserPage > Add FindBy

src/test/java/school/redrover/ViewsTest.java, src/test/java/school/redrover/model/MyViewsPage.java
https://trello.com/c/1voDTObw/2067-rf-myviewpage-delete-ignor-and-rf-tests
=> RF | MyViewPage > Delete Ignor and RF Tests

src/test/java/school/redrover/ViewsTest.java, src/test/java/school/redrover/model/component/MainBreadcrumbComponent.java
https://trello.com/c/R6HpfROs/2068-rf-myviewpage-delete-ignor-and-rf-tests
=> RF | MyViewPage > Delete Ignor and RF Test

src/test/java/school/redrover/model/BuiltInNodePage.java, src/test/java/school/redrover/model/TimelinePage.java
=> RF | TimelinePage, BuiltInNodePage > Add FindBy

src/test/java/school/redrover/HeaderTest.java
https://trello.com/c/os5VaVKk/2074-rf-headertest-refactoring-class-delete-dublicated-tests
=> RF Header > refactoring class> delete dublicated tests

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/LoginPage.java
=> RF 17.05 | Page-header > Logout btn > Log out button transfer the user back to the login page 'Welcome to Jenkins!'

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseConfigProjectsPage.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
https://trello.com/c/FWj99Tk6/2077-at-0104-freestyle-project-configure-enable-jenkins-to-block-builds-when-upstream-project-is-building
=> AT 01.04 | Freestyle Project > Configure > Enable Jenkins to block builds when upstream project is building

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/UsersTest.java
https://trello.com/c/DoCWxzHC/2079-rf-usertest-rf-old-test-to-pom
=> RF UserTest > rf old test to POM

src/test/java/school/redrover/model/BuildHistoryPage.java, src/test/java/school/redrover/model/EditBuildInformationPage.java, src/test/java/school/redrover/model/ErrorNodePage.java, src/test/java/school/redrover/model/LoginPage.java, src/test/java/school/redrover/model/ManageUsersPage.java, src/test/java/school/redrover/model/NewJobPage.java, src/test/java/school/redrover/model/RenamePage.java, src/test/java/school/redrover/model/ViewPage.java
=> RF  | Remove no usages methods

src/test/java/school/redrover/ViewsTest.java
ignore removed
RF - https://trello.com/c/jwqytRB5/2081-rf-viewstest-testmovefoldertonewviewlist
=> RF | ViewsTest > testMoveFolderToNewViewList

src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/ManageUsersPage.java
RF - https://trello.com/c/OOWoD7Vd
=> RF | UsersTest > old testMoveFolderToNewViewList to POM

src/test/java/school/redrover/model/ErrorNodePage.java, src/test/java/school/redrover/model/StatusUserPage.java, src/test/java/school/redrover/model/UserConfigPage.java
=> RF ErrorNodePage POM

src/test/java/school/redrover/model/ManageUsersPage.java, src/test/java/school/redrover/model/jobsconfig/PipelineConfigPage.java
=> RF | ManageUsersPage, PipelineConfigPage > replace locators in methods through annotation FindBy

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/MovePage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java, src/test/java/school/redrover/model/jobs/MultiConfigurationProjectPage.java
=> RF | MultiConfigurationProjectPage, MovePage, MainHeaderComponent > Add FindBy

src/test/java/school/redrover/BreadcrumbTest.java, src/test/java/school/redrover/model/component/MainBreadcrumbComponent.java
=> AT Item12.03 | Breadcrumb > Dashboard > Testing "Reload Configuration from Disk" could be done using Manage Jenkins submenu option

src/test/java/school/redrover/model/component/MainHeaderComponent.java
=> RF | MainHeaderComponent > refactoring methods' code with locators as parameter

src/test/java/school/redrover/FolderTest.java
=> RF | FolderTest> moveJobsToFolderFromSideMenu > Add prefixes "test"

src/test/java/school/redrover/FolderTest.java
=> RF | FolderTest > Delete test testFoldersCreationWithProvider

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/ViewsTest.java, src/test/java/school/redrover/model/CreateItemErrorPage.java
https://trello.com/c/kHCQLy3o/2116-rf-foldertest-testcreatenewviewinfolder-move-to-viewtest
=>  testCreateNewViewInFolder move to ViewTest

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/j3VgE8yc/2113-rf-folder-rename-name-of-tests
=> RF  | Folder > Rename name of Tests

src/test/java/school/redrover/FolderTest.java
AT TC 04.17 | Folder > Preview Description
=> AT TC 04.17 | Folder > Preview Description

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/ViewsTest.java, src/test/java/school/redrover/model/CreateItemErrorPage.java
https://trello.com/c/kHCQLy3o/2116-rf-foldertest-testcreatenewviewinfolder-move-to-viewtest
=> RF | FolderTest > testCreateNewViewInFolder move to ViewTest

src/test/java/school/redrover/ConfigureGlobalSecurityTest.java, src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/NewJobPage.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java, src/test/java/school/redrover/runner/TestUtils.java
=> RF | create method with Error in TestUtils for testCreateWithExistingName, testCreateFolderUsingInvalidData, createJobWithSpaceInsteadName

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/CreateItemErrorPage.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/base/BaseConfigPage.java, src/test/java/school/redrover/model/jobs/FolderPage.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
=> AT 04.02| Folder > Rename Folder from Side Menu

src/test/java/school/redrover/FolderTest.java
=> RF | FolderTest > Fix ignore > testCreateWithExistingName

src/test/java/school/redrover/model/base/BaseDashboardPage.java
=> RF | BaseDashboardPage ->verifyJobIsPresent

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/CreateItemErrorPage.java
=> AT 04.00| Folder > Create Folder with name " "

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/base/BaseJobPage.java
https://trello.com/c/SxUC1Gnn/2217-at-0405-folder-delete-folder-from-side-menu
=> AT 04.05 | Folder > Delete Folder from Side Menu

src/test/java/school/redrover/model/base/BaseDashboardPage.java
=> RF BaseDashboardPage : fix return page for some methods

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/runner/TestUtils.java
=> RF 04.12-16 | FolderTest > testMoveJobsToFolderFromSideMenu

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/jobs/FolderPage.java
=> AT 04.17 | Folder > Add Description

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/base/BaseJobPage.java, src/test/java/school/redrover/runner/TestUtils.java
=> AT 04.17 | Folder > Description - Preview

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/h16nZhV7/2266-at-0404-folder-configure-add-health-metrics
=> AT 04.04 | Folder > Configure > Add Health metrics

src/test/java/school/redrover/OrganizationFolderTest.java
=> AT 06.06 | OrganizationFolderTest > Configuration >testDeleteDisplayName

src/test/java/school/redrover/OrganizationFolderTest.java
=> АТ 06.04 | OrganizationFolderTest > Negative > testCreateWithExisting Name

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/OrganizationFolderTest.java
=> AT 06.04 | OrganizationFolderTest > Negative >testCreateEmptyName

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/base/BaseConfigFoldersPage.java
https://trello.com/c/1yMZ0QOb/2265-at-0404-folder-configure-folder-healthmetrics-delete
=> AT 04.04 | Folder > Configure Folder > HealthMetrics - Delete

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/8f5WhZR9/2111-tc-0417-folder-edit-description
=> testEditDescription

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
https://trello.com/c/wF3T2nWt/2264-rf-headertest-fixignore-testbuttonnotificationsworks
=> RF | HeaderTest > fix_ignore > testButtonNotificationsWorks

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/CreateBugPage.java, src/test/java/school/redrover/model/NewJobPage.java
=> AT 04.00| Folder > Create Folder with a long name

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/base/BaseOtherFoldersPage.java, src/test/java/school/redrover/model/jobsconfig/OrganizationFolderConfigPage.java
=> AT 06.06 | OrganizationFolderTest > Configuration > Enable From Config

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/yOeT4Ryb/2230-rf-organizationfoldertest-rf-testrenamenegative
=> RF | OrganizationFolderTest > rf testRenameNegative

src/test/java/school/redrover/OrganizationFolderTest.java
=> RF | OrganizationFolderTest > rf testDeleteOrganizationFolder

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/IbX2otZi/2228-rf-organizationfoldertest-refactoring-testrenameorganizationfolder
=> RF | OrganizationFolderTest > refactoring testRenameOrganizationFolder

src/test/java/school/redrover/OrganizationFolderTest.java
=> RF | OrganizationFolderTest > testCreateWithExistingName

src/test/java/school/redrover/FolderTest.java
=> RF | Folder > delete testCreateFromDashboard

src/test/java/school/redrover/FolderTest.java
=> RF | Folder > Create Folder with a long name

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/vF9gfWo7/2246-rf-organizationfoldertest-view-configuretestdisabledorganizationfolder
=> RF | OrganizationFolderTest >View/Configure>testDisabledOrganizationFolder

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/OrganizationFolderTest.java
=> AT 06.04 | OrganizationFolderTest >testCreateFromCreateAJob

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/base/BaseOtherFoldersPage.java
https://trello.com/c/QhQxPwGc/2289-at-0601-organizationfolder-enable-orgfolder-project-from-project-page
=> AT 06.01 | OrganizationFolder > Enable OrgFolder project From Project Page

src/test/java/school/redrover/OrganizationFolderTest.java
=> RF | OrganizationFolderTest > test rename > add dependency

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/NPcGwEcV/2293-rf-organizationfolder-rf-testadddescriptiontocreatedproject
=> RF | OrganizationFolder > rf testAddDescriptionToCreatedProject()

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/jobsconfig/PipelineConfigPage.java
=> AT 04.04 | Folder > Configure Folder > HealthMetrics - Recursive

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/ManageNodesPage.java, src/test/java/school/redrover/model/NodePage.java
https://trello.com/c/9G1Tv1XA
Create @Test testDeleteNodeBySideMenuOnNodePage()
=> AT 18.02 | Nodes > Delete agent node > Delete agent node by Side Menu on Node Page

src/test/java/school/redrover/OrganizationFolderTest.java
=> AT 06.06 | OrganizationFolderTest > Configuration > Add Health metrics

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/jobsconfig/OrganizationFolderConfigPage.java
=> AT 06.06 | OrganizationFolderTest > View/Configure >AppearanceIconHasChanged

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/ScanOrganizationFolderLog.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java, src/test/java/school/redrover/model/jobsconfig/OrganizationFolderConfigPage.java
https://trello.com/c/t0hxDysw/2295-at-0601-organizationfoldertest-view-configure-scan-organization-folder-log
=> AT 06.01 | OrganizationFolderTest > View/Configure >Scan Organization Folder Log

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/CredentialsPage.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java
https://trello.com/c/90EXeuh8/2248-tc-0601-organizationfoldertest-view-configure-credentials
=> TC 06.01 | OrganizationFolderTest > View/Configure >Credentials

src/test/java/school/redrover/model/CredentialsPage.java
TC 06.01 | OrganizationFolderTest > View/Configure >Credentials fix01
=> AT 06.01 | OrganizationFolderTest > View/Configure >Credentials fix01

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java
[TC](https://trello.com/c/z3fpSHPM/2253-tc-0601-organizationfoldertest-view-configure-creating-a-jenkins-pipeline)
[AT](https://trello.com/c/xKkoAsKf/2277-at-0601-organizationfoldertest-view-configure-creating-a-jenkins-pipeline)
=> AT_06_01OrganizationFolder_Creating_Jenkins_Pipeline

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/BuildWithParametersPage.java
=> RF | FreestyleProjectTest -> testPresenceOfBuildLinksAfterBuild

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java, src/test/java/school/redrover/model/jobsconfig/OrganizationFolderConfigPage.java
=> AT 06.01 | OrganizationFolderTest > View/Configure >Configure the project

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/ktsPNGmD/2310-at-organizationfoldertest-rename-testrenamewithinvaliddata
=> AT| OrganizationFolderTest > Rename >testRenameWithInvalidData

src/test/java/school/redrover/FolderTest.java
=> AT 04.04 | Folder > Configure > Description - delete

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/PipelineSyntaxPage.java, src/test/java/school/redrover/model/base/BaseOtherFoldersPage.java
https://trello.com/c/4JgMC3eA/2296-at-0000-item-sub-item-title
=> AT 06.01|OrganizationFolderTest>View/Configure>Pipeline Syntax

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/5GI5IPDN/2300-at-0604-organizationfoldertest-negative-testcreateorgfolderwithlongname
=> AT 06.04 | OrganizationFolderTest > Negative > testCreateOrgFolderWithLongName

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/V29GeHqk/2104-rf-0412-16-foldertest-testmovejobstofolderfromdropdownmenu
=> RF 04.12-16 | FolderTest > testMoveJobsToFolderFromDropDownMenu

src/test/java/school/redrover/BreadcrumbTest.java, src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FooterTest.java, src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/UsersTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/ManageJenkinsPage.java, src/test/java/school/redrover/model/base/BaseDashboardPage.java, src/test/java/school/redrover/model/component/MainBreadcrumbComponent.java, src/test/java/school/redrover/model/component/MainHeaderComponent.java
=> RF 00.00 | MainPage>move some methods to the MainBreadcrumbComponent, MainHeaderComponent, BaseDashboardPage

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/G3FLLED4/2337-rf-0406-11-foldertest
=> RF testCreateJobsInFolder

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProject > RF testCreatedNewBuild

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/OrganizationFolderEventsPage.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java
=> AT 06.01 | OrganizationFolderTest > View/Configure >Organization Folder Events

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProject > RF testDeleteProjectWithoutConfirmation()

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/phSNPkbR
**RF testVisibleProjectNameAndDescriptionOnViewPage:**
- убрать шаги по добавлению description из теста и проверку на description соответственно убрать
- поменять название теста на более соответвующее - тут проверяют ,что именно такое имя проекта отображается на странице проекта
=> RF | FreestyleProject > RF testVisibleProjectNameAndDescriptionOnViewPage

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/jobs/FolderPage.java
=> RF | Folder > testMoveJobsToFolderFromSideMenu

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/lGbMzb0p/2323-rf-organizationfolder-rename-rf-testrenameorganizationfolder
=> RF | OrganizationFolder > Rename > RF testRenameOrganizationFolder()

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/ZxaHKbJF/2312-rf-freestyleproject-rf-testcreatefreestyleproject
=> RF | FreestyleProject > rf testCreateFreestyleProject

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/Kzl5fFGk/2343-rf-organizationfolder-rf-testdeleteorganizationfolder
=> RF | OrganizationFolder > RF testDeleteOrganizationFolder()

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/yRMIQLAv/2318-rf-freestyleproject-rf-testrenamefreestyleproject
=> RF | FreestyleProject > RF testRenameFreestyleProject

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProject > RF testBuildFreestyleProject

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/DtaYxCUA/2346-rf-folder-rf-testdeletefolder
=> RF | Folder > RF testDeleteFolder()

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/UNmyjiGv/2375-at-0101-freestyleproject-create-job-with-long-name
=> AT 01.01 | FreestyleProject > Create job with Long Name

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/YTnltCTG/2314-rf-freestyleproject-rf-testemptynameerror
=> RF Freestyle project testCreateWithEmptyName()

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/3QAzF8AM/2351-rf-organizationfolder-rf-testenableorgfolderfromprojectpage
=> RF | OrganizationFolder > RF testEnableOrgFolderFromProjectPage()

src/test/java/school/redrover/FreestyleProjectTest.java
=> AT 01.06 | FreestyleProject >testRenameToTheCurrentNameAndGetError

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/5zeyCgbk/2350-rf-organizationfolder-rf-testdisableorgfolderfromprojectpage
=> RF | OrganizationFolder > RF testDisableOrgFolderFromProjectPage()

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/ejowMxgI/2365-rf-folder-rf-testpreviewdescription
=> RF | Folder > RF testPreviewDescription()

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProject > RF testPresenceOfBuildLinksAfterBuild

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/ZaUhc7MW/2355-rf-organizationfolder-rf-testdisabledorganizationfolder
=> RF | OrganizationFolder > RF testDisabledOrganizationFolder()

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProject > RF testCreateFreestyleProjectWithDescription()

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/8rBJXkhQ/2354-rf-organizationfolder-rf-testenableorgfolderfromconfig
=> RF | OrganizationFolder > RF testEnableOrgFolderFromConfig()

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/kZY4NkWW/2322-rf-folder-rename-rf-testrenamefromleftsidepanel
=> RF | Folder > Rename > RF testRenameFromLeftSidePanel()

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java
https://trello.com/c/t3Q2GggC/2369-tc-0606-organizationfolder-preview-description-from-project-page
=> TC 06.06 | OrganizationFolder >Preview Description From Project Page

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/rdRZkLua/2313-rf-freestyleproject-rf-testcreatefsprojectwithdefaultconfigurations
=> RF | FreestyleProject > RF testCreateFSProjectWithDefaultConfigurations

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/YT72HKud/2320-rf-freestyleproject-rf-testrenamefreestyleprojectusingdropdownmenu
=> RF | FreestyleProject > RF testRenameFreestyleProjectUsingDropDownMenu

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/BkfFwqer/2338-rf-folder-rf-testcreatefolderwithlongname
=> RF | Folder > RF testCreateFolderWithLongName

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/sKlJBBMX/2326-rf-folder-rf-testcreatefolderusinginvaliddatastring-invaliddata
=> RF | Folder > RF testCreateFolderUsingInvalidData(String invalidData)

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/30GPQgTf/2386-rf-folder-rf-testrenameusingdropdownmenu
=> RF | Folder > RF testRenameUsingDropDownMenu()

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/DQGlitze/2336-rf-folder-rf-testcreatefolderwithspaceinsteadname
=> RF | Folder > RF testCreateFolderWithSpaceInsteadName()

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/b47zED4Z/2342-rf-folder-rf-testdeletefolderfromsidemenu
=> RF | Folder > RF testDeleteFolderFromSideMenu()

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/Bs6jZ7Fr/2339-rf-folder-rf-testrenamefolderwithinvaliddatastring-invaliddata
=> RF | Folder > RF testRenameFolderWithInvalidData(String invalidData)

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/9T8BMlgy/2370-rf-organizationfolder-rf-testadddescriptiontoproject
=> RF | OrganizationFolder > RF testAddDescriptionToProject()

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/JfKF2fR8/2335-rf-organizationfolder-rf-testcreateorganizationfolderwithspacename
=> RF | OrganizationFolder > RF testCreateOrganizationFolderWithSpaceName()

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseDashboardPage.java
https://trello.com/c/gfyM2LG7
создать тест с названием testDisableFromConfigurationPage
=> AT 01.04 | FreestyleProject > Configuration > Disable Project

pom.xml
=> RF | add Allure

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
=> AT 01.04 | FreestyleProject > Configuration > Post build actions > E-mail Notification

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java
=> AT 06.01 | OrganizationFolderTest > View/Configure >Re-run the Folder Computation

src/test/java/school/redrover/FolderTest.java
[AT 04.00 | Folder > Error when creating Folder with name '.'(dot)](https://trello.com/c/B9c5dmbp)
=> AT 04.00 | Folder > Error when creating Folder with name '.'(dot)

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/rjD574nT/2348-rf-freestyleproject-rf-testdisableproject
=> RF | FreestyleProject > RF testDisableProject()

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/ZQ8C4Ai4/2391-at-0000-item-sub-item-title
=> AT 06.04 | OrganizationFolder > Create job with name "."

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProject > RF testPreviewDescription

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/F1DB16mL/2349-rf-freestyleproject-rf-testenableproject
=> RF | FreestyleProject > RF testEnableProject()

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/Mrog2XHQ/2400-at-freestyleproject-rename-testrenamewithinvaliddatastring
=> AT FreestyleProject >Rename> testRenameWithInvalidData(String)

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseConfigPage.java
=> AT 01.04 | Freestyle Project > Configure > access the Configuration page of a FP from the Dashboard

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/LcGXsctR/2361-rf-freestyleproject-rf-testadddescriptionfromconfiguredropdownandpreview
=> RF | FreestyleProject > RF testAddDescriptionFromConfigureDropDownAndPreview()

src/test/java/school/redrover/FolderTest.java
Combine testErrorCreateWithDotNameFromCreateAJob and testOkButtonCreateWithDotNameFromCreateAJob to one test with two asserts
https://trello.com/c/ImtkDKG8/2417-rf-folder-rf-unit-two-test-to-one-test-testerrorcreatewithdotnamefromcreat-eajobtestokbuttoncreatewithdotnamefromcreateajo
=> RF 04.00 RF | Folder > RF unit two test To one test 

src/test/java/school/redrover/OrganizationFolderTest.java
=> RF | OrganizationFolder > RF testOrganizationFolderConfigPreviewDescription

src/test/java/school/redrover/FolderTest.java
=> RF | Folder > testMoveJobsToFolderFromDropDownMenu

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/4sTp5q1g/2347-rf-freestyleproject-rf-testdeleteprojectfromdropdown
=> RF | FreestyleProject > RF testDeleteProjectFromDropdown

src/test/java/school/redrover/FolderTest.java
=> RF | Folder > RF testAddDescriptionPreview

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/OrX199MR/2491-rf-freestyleprojecttest-testdisablefromprojectpage
=> RF | FreestyleProjectTest > testDisableFromProjectPage

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/OrganizationFolderTest.java
=> RF | OrganizationFolderTest > rf testCreateOrganizationFolder

src/test/java/school/redrover/FolderTest.java
=> RF | Folder > RF testAddDescriptionFromFolderPage

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/Q2gdalTO/2431-rf-freestyleproject-delete-testcreatefsprojectwithdefaultconfigurations
=> RF | FreestyleProject > Delete testCreateFSProjectWithDefaultConfigurations

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/JQlFBi11/2452-rf-organizationfolder-rf-testcreateorganizationfoldergoingfrommanagejenkinspage
=> RF | OrganizationFolder > RF testCreateOrganizationFolderGoingFromManageJenkinsPage()

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/7TwgloEH/2494-at-0000-item-sub-item-title
=> AT 01.01 | FreestyleProject > Create job with invalid name

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/PipelineProjectPage.java, src/test/java/school/redrover/model/jobs/OrganizationFolderPage.java
[RF](https://trello.com/c/oXaPxUMy/2489-rf-organizationfoldertest-view-configure-creating-a-jenkins-pipeline)
=> RF_OrganizationFolderTest_View_Configure_CreatingJenkinsPipeline

src/test/java/school/redrover/FolderTest.java
add testCreateFromPeoplePage()
https://trello.com/c/XYYxAnhn/2496-at-0400-folder-testcreatefrompeoplepage
=> AT 04.00 | Folder > testCreateFromPeoplePage

src/test/java/school/redrover/OrganizationFolderTest.java
=> AT 06.04 | OrganizationFolder >testCreateFromMyViewsNewItem

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/zK0MPVIK/2490-rf-freestyleproject-build-now-rf-testcreatednewbuild
=> RF | FreestyleProject > Build Now > RF testCreatedNewBuild

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/runner/TestUtils.java
=> RF | Folder > testCreateJobsInFolder

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/base/BaseProjectPage.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
=> AT 01.04 | FreestyleProject > Configuration > Post build actions > Build other projects

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/MultiConfigurationProjectTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/PipelineTest.java, src/test/java/school/redrover/model/NewJobPage.java
=> RF | NewJobPage > isOkButtonDisabled

src/test/java/school/redrover/FolderTest.java
=> AT 04.05 | Folder >testCancelDeletingFromDropDownMenu

src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/component/MainBreadcrumbComponent.java
=> RF | OrganizationFolder >testCreateFromMyViewsNewItem

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/base/BaseJobPage.java
https://trello.com/c/loqwLBds/2493-at-0404-folder-add-description-from-configuration-page
=> AT 04.04 | Folder > Add Description From Configuration Page

src/test/java/school/redrover/FolderTest.java
=> RF | Folder > RF testCreateFolderGoingFromBuildHistoryPage

src/test/java/school/redrover/FreestyleProjectTest.java
=> AT 01.01 | FreestyleProject >testCreateFromMyViewsCreateAJob

src/test/java/school/redrover/FreestyleProjectTest.java
=> AT 01.01 | FreestyleProject testCreateFromManageJenkinsPage

src/test/java/school/redrover/FolderTest.java
=> TC 04.04 | Folder> Add Health Metrics From SideMenu

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/3F3J6PXh/2536-rf-organizationfolder-rf-testdeleteorganizationfolderfromthedropdownmenu
=> RF | OrganizationFolder > RF testDeleteOrganizationFolderFromTheDropdownMenu()

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/zX78U0ef/2423-rf-folder-testconfigurefoldernamedescriptionhealthmetrics
=> RF | Folder > testConfigureFolderNameDescriptionHealthMetrics

src/test/java/school/redrover/OrganizationFolderTest.java
=> AT 06.01 | Organization Folder > testPreviewDescriptionFromProjectPage

src/test/java/school/redrover/model/base/BaseConfigFoldersPage.java
=> RF | OrganizationFolder > RF testAddHealthMetricsSideMenu

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
RF testFreestyleProjectJob
rename to testBuildStepsInvokeMavenGoalsTargets
https://trello.com/c/Cr5eVznm/2317-rf-freestyleproject-rf-testfreestyleprojectjob
=> RF | FreestyleProject > RF testFreestyleProjectJob

src/test/java/school/redrover/FreestyleProjectTest.java
[AT 01.04 | Freestyle Project > Configure > access Configuration page Configuration page from a FP](https://trello.com/c/BjtepFg9)
=> AT 01.04 | Freestyle Project > Configure > access Configuration page Configuration page from a FP

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/ManageNodesPage.java
[https://trello.com/c/9BWNzuGK](https://trello.com/c/9BWNzuGK)
Create test testDeleteNodeByDropDownOnManageNodesPage()
=> AT 18.02 | Nodes > Delete agent node > Delete agent node by Drop Down Menu on Manage Nodes Page

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/0J7TLkOH/2541-at-0400-folder-testcreatefrommyviewsnewitem
=> AT 04.00 | Folder > testCreateFromMyViewsNewItem

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/ZDuRSAxd/2540-rf-folder-rf-testeditdescription
=> RF | Folder > RF testEditDescription()

src/test/java/school/redrover/FolderTest.java
https://trello.com/c/bjA1YQ4S/2542-at-0400-folder-testcreatefrommyviewscreateajob
=> AT 04.00 | Folder > testCreateFromMyViewsCreateAJob

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
=> AT 01.04 | FreestyleProject > Configure > General>Advanced >Display Name

src/test/java/school/redrover/FolderTest.java
=> AT 04.00 | Folder > Create job>testCreateWithEmptyName

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/model/jobsconfig/FolderConfigPage.java
=> Add test added pipeline libraries

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/n27DTFTQ/2551-at-0101-freestyleproject-testcreatefrommyviewscreateajobarrow
=> AT 01.01 | FreestyleProject > testCreateFromMyViewsCreateAJobArrow

src/test/java/school/redrover/OrganizationFolderTest.java
=> AT 06.04 | OrganizationFolder > testCreateFromMyViewsCreateAJob

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/jobsconfig/FolderConfigPage.java
=> RF | FolderTest > depends & RF | FolderTest > testAddedPipelineLibrar

src/test/java/school/redrover/FreestyleProjectTest.java
=> AT 01.03 | FreestyleProject > Build Now>testCreateBuildNowFromArrow

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/ChangesPage.java, src/test/java/school/redrover/model/base/BaseProjectPage.java
=> AT 01.03 | FreestyleProject > Build Now > Changes From Project Page

src/test/java/school/redrover/FolderTest.java
=> RF | FolderTest > tests in order

src/test/java/school/redrover/FolderTest.java
=> AT 04.00 | Folder > testCreateFromManageJenkinsPage

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/RfCTGXXu/2573-at-0101-freestyleproject-testcreatefrompeoplepage
=> AT 01.01 | FreestyleProject >testCreateFromPeoplePage

src/test/java/school/redrover/FolderTest.java
=> AT 04.00 | Folder >testCreateFromMyViewsCreateAJobArrow

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/XgVBaIdK/2579-at-freestyleproject-create-job-testcreatefrombuildhistorypage
=> AT| FreestyleProject > Create job >testCreateFromBuildHistoryPage

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/VdPsRHxv/2581-at-0604-organizationfolder-testcreatefrompeoplepage
=> AT 06.04 | OrganizationFolder >testCreateFromPeoplePage

src/test/java/school/redrover/FolderTest.java
=> AT 04.04 | Folder >testAccessConfigurationPageFromSideMenu

src/test/java/school/redrover/FolderTest.java
=> AT 04.04 | Folder >testAccessConfigurationPageFromDashboard

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/XtO5hfG0/2584-at-0604-organizationfolder-create-job-testcreatefrombuildhistorypage
=> AT 06.04 | OrganizationFolder > Create job >testCreateFromBuildHistoryPage

src/test/java/school/redrover/OrganizationFolderTest.java
=> AT | OrganizationFolder | Create job >testCreateFromCreateAJobArrow

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/base/BaseDashboardPage.java
https://trello.com/c/QrxRUqZb/2559-at-0000-item-sub-item-title
=> AT 01.03 | FreestyleProject > Build Now>testDeleteBuildNowFromDropDown

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
=> AT 01.04 | FreestyleProject > Configure >Build Steps >testBuildStepsDropdownOptions

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
[AT] https://trello.com/c/vmdUqbEg
=> AT 01.04 | FreestyleProject > Configuration > Post build actions > Git Publisher

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/XTaXRi32/2572-rf-organizationfoldertest
=> RF | OrganizationFolderTest >putting the tests in the right order

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/WorkspacePage.java, src/test/java/school/redrover/model/base/BaseProjectPage.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
https://trello.com/c/yZQYvFRo/2583-at-0104-freestyleproject-configuration-post-build-actions-delete-workspace-when-build-is-done
add testDeleteWorkspaceWhenBuildDonePostBuildActions()
=> AT 01.04 | FreestyleProject > Configuration > Post build actions > Delete workspace when build is done

src/test/java/school/redrover/FreestyleProjectTest.java
=> AT 01.01 | FreestyleProject > Create job with name "."

src/test/java/school/redrover/ConfigureSystemTest.java, src/test/java/school/redrover/model/ConfigureSystemPage.java, src/test/java/school/redrover/model/ManageJenkinsPage.java
added testManageJenkinsEmailNotificationSetUp
TC https://trello.com/c/R9q4OU6b
=> TC 09.10 | Manage Jenkins > Configure system > Editable Email Notification

src/test/java/school/redrover/BuildPageTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/OrganizationFolderTest.java, src/test/java/school/redrover/model/EditBuildInformationPage.java, src/test/java/school/redrover/model/base/BaseDashboardPage.java, src/test/java/school/redrover/model/base/BaseProjectPage.java
https://trello.com/c/02dJJ0y1/2568-at-0103-freestyleproject-build-now-testeditbuildinformationfromprojectpage
=> AT 01.03 | FreestyleProject > Build Now >testEditBuildInformationFromProjectPage

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/YvUC5iEm/2604-at-0601-organizationfolder-view-configure-testrenamewithdotname
=> AT 06.01 | OrganizationFolder > View/Configure > testRenameWithDotName

src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/gQJUyF40/2605-rf-freesty
=> RF | FreestyleProject| testCreateFromPeoplePage

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseDashboardPage.java
=> AT 01.03 | FreestyleProject > Build Now> testConsoleOutputFromDropDown

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/worh7kR9/2607-at-0606-organizationfolder-testaccessconfigurationpagefromsidemenu
=> AT 06.06 | OrganizationFolder >testAccessConfigurationPageFromSideMenu

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseDashboardPage.java, src/test/java/school/redrover/model/base/BaseModel.java
https://trello.com/c/WQ3H3Lsd/2609-at-0103-freestyleproject-build-now-edit-build-information-from-dropdown-menu
=> AT 01.03 | FreestyleProject > Build Now > Edit Build Information From DropDown Menu

src/test/java/school/redrover/ConfigureSystemTest.java, src/test/java/school/redrover/model/ConfigureSystemPage.java
added testManageJenkinsEmailNotificationGoingBackToOriginalSettings
RF https://trello.com/c/TRji5wC2
=> TC 09.10 | Manage Jenkins > Configure system > Return to original settings Editable Email Notification

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseProjectPage.java
https://trello.com/c/qCNdPS8N/2606-at-0103-freestyleproject-build-now-testconsoleoutputfromprojectpageadd testConsoleOutputFromProjectPage()
=> AT 01.03 | FreestyleProject > Build Now > testConsoleOutputFromProjectPage

src/test/java/school/redrover/FolderTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseProjectPage.java
=> AT 01.03 | FreestyleProject > Build Now > Changes From Last Build

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/BuildPage.java, src/test/java/school/redrover/model/DeletePage.java, src/test/java/school/redrover/model/base/BaseDashboardPage.java
=> RF | FreestyleProject > testDeleteBuildNowFromDropDown

src/test/java/school/redrover/OrganizationFolderTest.java
https://trello.com/c/gxNL3Dxm/2610-rf-organizationfolder-movet-estaccessconfigurationpagefromdashboard
=> RF | OrganizationFolder > movet estAccessConfigurationPageFromDashboard()

src/test/java/school/redrover/FreestyleProjectTest.java
=> RF | FreestyleProject > RF class > Delete all dependsOfMethod

src/test/java/school/redrover/BreadcrumbTest.java, src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/jobsconfig/FreestyleProjectConfigPage.java
=> AT01.04 | FreestyleProject> Build Steps >Execute Windows batch command

src/test/java/school/redrover/model/CreateUserPage.java
=> RF | CreateUserPage > check locators

src/test/java/school/redrover/model/NewViewPage.java
=> RF | NewViewPage > check locators

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/baseConfig/BaseConfigFreestyleAndMulticonfigProjectsPage.java
=> AT 01.04 | FreestyleProject > Configure > General >Advanced>Use custom workspace

src/test/java/school/redrover/ViewsTest.java, src/test/java/school/redrover/model/IncludeAGlobalViewConfigPage.java, src/test/java/school/redrover/model/ListViewConfigPage.java, src/test/java/school/redrover/model/MyViewConfigPage.java
=> AT 11.05 Views > Edit description > edit description for all type of view

src/test/java/school/redrover/UsersTest.java
=> RF | Users >RF testAddDescriptionToUserOnTheUserProfilePage()

src/test/java/school/redrover/FreestyleProjectTest.java, src/test/java/school/redrover/model/base/BaseProjectPage.java
=> AT 01.04 | FreestyleProject > Configuration> Enable Project

src/test/java/school/redrover/UsersTest.java
=> RF | Users > delete testVerifyCreateUserButton()

src/test/java/school/redrover/ViewsTest.java, src/test/java/school/redrover/model/ViewPage.java
=> RF | ViewPage > check locators

src/test/java/school/redrover/ManageJenkinsTest.java, src/test/java/school/redrover/model/ManageNodesPage.java
=> RF | ManageNodesPage > add Steps

src/test/java/school/redrover/DashboardTest.java, src/test/java/school/redrover/model/MainPage.java, src/test/java/school/redrover/model/MyViewsPage.java, src/test/java/school/redrover/model/ViewPage.java, src/test/java/school/redrover/model/base/BaseDashboardPage.java, src/test/java/school/redrover/model/interfaces/IViewBar.java, src/test/java/school/redrover/model/jobs/FolderPage.java
=> RF | create Interface IViewBar

src/test/java/school/redrover/BuildHistoryTest.java, src/test/java/school/redrover/model/jobsConfig/PipelineConfigPage.java
=> RF | PipelineConfigPage > add Steps

src/test/java/school/redrover/HeaderTest.java, src/test/java/school/redrover/model/builds/BuildWithParametersPage.java
=> RF | BuildWithParametersPage > add Steps

src/test/java/school/redrover/ViewsTest.java
=> AT 11.05 | Views > Add description > add description for all type of view

src/test/java/school/redrover/model/jobsSidemenu/PipelineSyntaxPage.java
=> RF | PipelineSyntaxPage > add Steps

src/test/java/school/redrover/BuildHistoryTest.java, src/test/java/school/redrover/runner/BaseTest.java, src/test/java/school/redrover/runner/ProjectUtils.java, src/test/resources/testng.xml
=> Test2 add firefox
