- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
added AlexLeoEpicGroupTest.java class with test
> added AlexLeoEpicGroupTest.java class with test

- src/test/java/school/redrover/Group99BottlesTest.java
My first test added to group99BottlesTest
> First test added <verafes>

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
> Second Commit and Push Test

- src/test/java/school/redrover/AndreiAfanasevTest.java
> AA-TestRequest

- src/test/java/school/redrover/IrinaITest.java
> First test here

- src/test/java/school/redrover/BugsBustersTest.java
> First test

- src/test/java/school/redrover/EvgenyZagrebelnikovTest.java
added testOpenweatherGoogleSearch
> EvgenyZagrebelnikovTest

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
add saleTest TC_001
refactored 3 methods
> add saleTest TC_001

- src/test/java/school/redrover/CatCatchyNargiz.java
Added two tests for text verification and for drag and drop functionality.
> CatCatchy group Nargiz, added two tests

- src/test/java/school/redrover/AnnaMayTest.java
created new tests for USPS web application
> First commit with 3 tests

- src/test/java/school/redrover/GroupOlesyaTests.java
adding my first tests to GitHub
> adding my first tests to GitHub

- src/test/java/NafisaIsan.java
- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
my first push to Jenkins project
> my first tect for JenkinsProject

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
> Added TC003_33_ArtemT_verifyFindMoreLink

- src/test/java/school/redrover/ComradesAdelanteTest.java
Added first tests in this project
> Added first tests in this project

- src/test/java/school/redrover/AnaBelTest.java
- src/test/java/school/redrover/ComradesAdelanteTest.java
- src/test/java/school/redrover/GroupTwentyThreeTest.java
> Add JavaTutorial test

- src/test/java/school/redrover/UndercoverGroupTest.java
> Undercover

- src/test/java/school/redrover/AnaBelTest.java
- src/test/java/school/redrover/ComradesAdelanteTest.java
- src/test/java/school/redrover/GroupJasperAutomationTest.java
- rename class
- add test for title
> - rename class

- src/test/java/NafisaIsan.java
- src/test/java/school/redrover/BugsBustersTest.java
- src/test/java/school/redrover/ComradesAdelanteTest.java
- src/test/java/school/redrover/JavaNiSyTest.java
- src/test/java/school/redrover/TestSalary.java
- src/test/java/school/redrover/bond4562Test.java
- src/test/java/school/redrover/testSalary.java
Add 1 test dor calculation salary
> add test for calculation salary

- src/test/java/school/redrover/BugsBustersTest.java
- src/test/java/school/redrover/GroupAndreyTest.java
- src/test/java/school/redrover/GroupJavaExplorersTest.java
- src/test/java/school/redrover/JavaNiSyTest.java
> test title

- src/test/java/school/redrover/GroupOlesyaTests.java
> Add first tests

- src/test/java/school/redrover/PolinaSheverTest.java
USPS search by ZIP and address.
Verify the array list is returned and contains the provided ZIP.
> My first test

- src/test/java/school/redrover/AnnaMayBeforeAfterAnnotationTest.java
- src/test/java/school/redrover/ZeroBugTest.java
> First commit for ZeroBug

- src/test/java/AlexFTest.java
> Add AlexF first test to the repository

- src/test/java/school/redrover/AlexFTest.java
Move AlexF first test to school.redrover folder
> Move AlexF first test to school.redrover folder

- src/test/java/school/redrover/SergeyDTest.java
- src/test/java/school/redrover/VladLiTest.java
> Vlad brench

- src/test/java/school/redrover/UndercoverGroupTest.java
> Lord iktor

- src/test/java/school/redrover/GroupUkrTest.java
> Test comment

- src/test/java/school/redrover/BugsBustersTest.java
Fun art colorado first test
Test name "testMS"
> fun-art-colorado

- src/test/java/school/redrover/GroupJavaJitsu.java
> Anton first commit

- src/test/java/school/redrover/ComradesAdelanteTest.java
- src/test/java/school/redrover/Group99BottlesTest.java
Created testTelerikHeaderText() Group99Bottles_NO
> Created testTelerikHeaderText() Group99Bottles_NO

- src/test/java/school/redrover/Group99BottlesTest.java
Created testTelerikTitleURLDemosPage() Group99Bottles_NO
> testTelerikTitleURLDemosPage() Group99Bottles_NO

- src/test/java/school/redrover/BestAutoTeamTest.java
- src/test/java/school/redrover/GroupJavaJitsu.java
> Add first test

- src/test/java/school/redrover/UndercoverGroupTest.java
> Some optimisation

- src/test/java/NadiiaYuTest1.java
> first test NadiiaYu

- src/test/java/school/redrover/HelloWorldTest.java
> Bazhbranch

- src/test/java/school/redrover/Group99BottlesTest.java
- src/test/java/school/redrover/GroupJavaExplorersTest.java
Created testTelerikNavigateMenuDemosPage() Group99Bottles_NO
> testTelerikNavigateMenuDemosPage() Group99Bottles_NO

- src/test/java/school/redrover/Group99BottlesTest.java
Created testTelerikNavigateMenuDemosPageList() Group99Bottles_NO
> testTelerikNavigateMenuDemosPageList() Group99Bottles_NO

- src/test/java/school/redrover/OlhaKTest.java
First test in selenoum by Olha Kovanova
> Oko first test

- src/test/java/school/redrover/GroupOlesyaTests.java
Пробный тест не в общем стиле, хочу потом его удалить.
> My first test testUGLogOut

- src/test/java/school/redrover/StasM.java
> Stas m/secondtest

- pom.xml
- src/test/java/school/redrover/GroupJavaJitsu.java
> Java jitsu tema test

- src/test/java/school/redrover/GroupJavaExplorersTest.java
- src/test/java/school/redrover/GroupJavaJitsu.java
> agTest added

- src/test/java/school/redrover/BugsBustersTest.java
> Ignore first test

- src/test/java/school/redrover/DmTest.java
> Add the smoke DmTest

- src/test/java/school/redrover/BugsBustersTest.java
> fun-art-colorado-VideoTest

- src/test/java/school/redrover/AnnaMayBeforeAfterAnnotationTest.java
- src/test/java/school/redrover/Group99BottlesTest.java
> Add demoblaze test

- src/test/java/school/redrover/CaramelSurupForJavaTest.java
> Test Winner Phone Numbers

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
First test in group AlexLeoEpicGroupTest by Teymur (TC_008_Verify_click_FindMore_Button_Redirects_To_ContactUs_AlexLeoEpicGroupTest_TeymurTest)
> TC_008_Verify_FindMore_Button_Redirects_To_ContactUs_AlexLeoEpicGroupTest_TeymurTest

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
TC_007.02 Teymur - Men Page | Search Bar: Verify the background color of the "Search" button
> TC_007_02_Teymur_MenPage_Search Bar_Verify_backgroundColor_Search_button

- src/test/java/school/redrover/GroupCAT.java
> AT - Maksim24 - testClickDocumentationButton

- src/test/java/school/redrover/AliaksandraAnufryievaTest.java
- src/test/java/school/redrover/Group99BottlesTest.java
- src/test/java/school/redrover/HelloWorldTest.java
> AE/Update HelloWorldTest.java

- src/test/java/AndriiKudlaTest.java
> AndriiKudlaTest

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
- src/test/java/school/redrover/HelloWorldTest.java
> test refactoring

- src/test/java/school/redrover/Group99BottlesTest.java
- src/test/java/school/redrover/GroupUkrTest.java
> Alex s/first test

- src/test/java/school/redrover/GroupOlesyaTests.java
Тренируюсь, это бессмыссленный тест=)
> add my test logout2

- src/test/java/school/redrover/GroupSomeGroupTest.java
added testVerifyTitle to class GroupSomeGroupTest
> testVerifyTitle

- src/test/java/school/redrover/GroupOlesyaTests.java
> removing old tests

- src/test/java/school/redrover/AliaksandraAnufryievaTest.java
- src/test/java/school/redrover/AnaBelTest.java
- src/test/java/school/redrover/GroupJasperAutomationTest.java
- src/test/java/school/redrover/SeleniumFirstScriptTest.java
* Changes for BaseTest (#504)
* Add extension (#506)
* Add extension
* Add Ignore
---------
> JuliaCher first test (#512)

- src/test/java/school/redrover/BugsBustersTest.java
extend BaseTest to BugBustersTest class;
cancel Ignore;
refactor 2 tests (rename and refactor using BaseTest); 
reduce thread.sleep() duration
> refactoring first and second test

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
> refactoring

- src/test/java/school/redrover/Group99BottlesTest.java
> testLogoNavigateToBaseUrl<galinasedunova>

- src/test/java/school/redrover/GroupForwardTest.java
> add testFirst

- src/test/java/school/redrover/Group99BottlesTest.java
Refactoring Telerik tests, code cleaned, inore delited, wait added
> Refactoring Telerik tests Goup99Bottles_NO

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
> add new test

- src/test/java/school/redrover/GroupForwardTest.java
GroupForwardTest->Refactor sauceDemoLoginSuccessTest
> GroupForwardTest->Refactor sauceDemoLoginSuccessTest

- src/test/java/school/redrover/GroupJavaExplorersTest.java
> testEquilateralTriangleAdd

- src/test/java/school/redrover/UndercoverGroupTest.java
> BeforeTest added +hotfix

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
Поставила аннотацию игнор к тесту Руслана testSubscripton
> Refactor testBlockPromo() and testTitle()

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
- src/test/java/school/redrover/BugsBustersTest.java
- src/test/java/school/redrover/GroupGlukhovaTest.java
- renaming tests, removing code that is already existed in BaseTest class
> Refactoring 8 tests

- src/test/java/school/redrover/UndercoverGroupHDTest.java
- src/test/java/school/redrover/runner/BaseTest.java
По умолчанию, без указания сеттера - 1920х1080
> Добавил возможность объявления в BeforeMethod разрешения окна браузера

- src/test/java/school/redrover/GroupGlukhovaTest.java
Refactor code: rename methods, remove extra timeouts
Add extends class BaseTest
Add test: availability to send a message using the contacts tab
> Refactoring code and add send message test

- src/test/java/school/redrover/ZeroBugTest.java
> New third test was added

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
testAddProductToCartInscription added
> AlexLeoGroup

- src/test/java/school/redrover/GroupJasperAutomationTest.java
> Use BaseTest Class

- src/test/java/school/redrover/GroupOlesyaTests.java
> add overloading loginToSite() method

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
- src/test/java/school/redrover/GroupJavaJitsuTest.java
>  fix training test (again) -Sergi

- src/test/java/school/redrover/GroupSomeGroupTest.java
> Refactor testVerifyTitle

- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
- src/test/java/school/redrover/GroupJavaExplorersTest.java
Added _testElementWithDynamicId_
Added _testClickOnButton_
Deleted _vhodTextOnAuthPageTest_
> Added 2 new tests. Deleted 1 old test.

- src/test/java/school/redrover/CaramelSurupForJavaTest.java
- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
test moved from duplicated class
> test moved from duplicated class

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
- src/test/java/school/redrover/GroupJasperAutomationTest.java
- src/test/java/school/redrover/GroupUkrTest.java
Add testHoodiesAndSweatshirtsHeader, delete unnecessary dependencies, ignore testOrderIphone14, ignore testAuthorizationAndLogOut
> Add testHoodiesAndSweatshirtsHeader

- src/test/java/school/redrover/Group99BottlesTest.java
refactoring my test in class Group99BottlesTest
> [RF] testCheckboxesHeadHerokuApp():Group99BottlesTest

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
Add test testVerifyAccountLink
> alexLeoGroupArtem

- src/test/java/school/redrover/BugsBustersTest.java
> Added testMariaLogin

- src/test/java/school/redrover/GroupCATTest.java
- src/test/java/school/redrover/JavaExpertsTest.java
testVerifyRedirectFromJetLabel() into POM
> testVerifyRedirectFromJetLabel was changed

- src/test/java/school/redrover/AndreyPomazTest.java
- src/test/java/school/redrover/Group99BottlesTest.java
- src/test/java/school/redrover/GroupHighwayToAqaTest.java
- src/test/java/school/redrover/LoginPageTest.java
Add testToolbarActionsOnWishListPageAreClickable() to GroupHigwayToAqaTest
> Add testToolbarActionsOnWishListPageAreClickable()

- src/test/java/school/redrover/AlexFTest.java
Refactor all tests with the recent Sergey requirements: delete all tests and created a new one
> Refactor all tests with the the new requirements

- src/test/java/school/redrover/GroupSomeGroupTest.java
> ElNov686 testButtonPrevious

- src/test/java/school/redrover/Group99BottlesTest.java
- src/test/java/school/redrover/GroupGlukhovaTest.java
Add testTelerikNavigateMenuDemosPageSize() and method getListSize(), count navigateMenuDemosPage buttons
> testTelerikNavigateMenuDemosPageSize() group99Bottles_NO

- src/test/java/school/redrover/BugsBustersTest.java
> Added testMariaAddItemsToCart

- src/test/java/school/redrover/Group99BottlesTest.java
1. refactor testLogoNavigateToBaseUrl
2. add testButtonsNames
> testButtonsNames<group99Bottles>

- src/test/java/school/redrover/GroupForwardTest.java
>  Add testOrchidCareIndoors

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
Add test TC_010 testVerifyAllProductsAreAscending
> alexLeoGroup_33

- src/test/java/school/redrover/ComradesAdelanteTest.java
Remake3_TestFirstAG_and_rename_to_testFirstAddRemoveElementAnnaG<annetta.glumova@gmail.com>
> Remake3_TestFirstAG

- src/test/java/school/redrover/GroupOlesyaTests.java
- src/test/java/school/redrover/JavaExpertsTest.java
refactor checkItemsTest and checkSortingTest, create selectTypeOfSortingItems method
> refactor class code

- src/test/java/school/redrover/AlexFTest.java
- src/test/java/school/redrover/BugsBustersTest.java
- src/test/java/school/redrover/ListOfFoodTest.java
- src/test/java/school/redrover/OrthazoneLoginLogoutTest.java
Refactor test title, @Ignored failed tests
> Refactor test title

- src/test/java/school/redrover/Group99BottlesTest.java
Change testH1Text_WhenChooseLevelLanguage()
> TestH1Text_WhenChooseLevelLanguage

- src/test/java/school/redrover/GroupJasperAutomationTest.java
> Add find element test

- src/test/java/school/redrover/OrthazoneLoginLogoutTest.java
> Refactor My Tests

- src/test/java/school/redrover/Group99BottlesTest.java
added testNumberOfButtonsAndTextsInSideMenu
> testNumberOfButtonsAndTextsInSideMenu<Group99Bottles>

- src/test/java/school/redrover/GroupOlesyaTests.java
rename methods: productNames() -> listProductNames()
goToShoppingCartPage() ->clickIconShoppingCart()
reactBurgerMenu() -> clickBurgerMenu()
delete method getListOfItemInCart();
add methods clickRemoveButton()
isElementPresent
> refactor removeFromCartTest

- src/test/java/school/redrover/Group99BottlesTest.java
add testHeaderTextOnSalePage()
> Add testHeaderTextOnSalePage() <Group99Bottles>

- src/test/java/school/redrover/AndreyPomazTest.java
- src/test/java/school/redrover/GroupForwardTest.java
- src/test/java/school/redrover/GroupJavaJitsuTest.java
> add testFirst1

- src/test/java/school/redrover/HelloWorldTest.java
Fix test PageTitle, add test DoubleClickButton
> Fix and add tests

- src/test/java/school/redrover/AlexLeoEpicGroupTest.java
- src/test/java/school/redrover/AndreyPomazTest.java
- src/test/java/school/redrover/BarbaraTest.java
- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
- src/test/java/school/redrover/ComradesAdelanteTest.java
- src/test/java/school/redrover/DreamTeamTest.java
- src/test/java/school/redrover/Group99BottlesTest.java
- src/test/java/school/redrover/GroupAnaBelsTest.java
- src/test/java/school/redrover/GroupHighwayToAqaTest.java
- src/test/java/school/redrover/GroupJasperAutomationTest.java
- src/test/java/school/redrover/GroupJavaJitsuTest.java
- src/test/java/school/redrover/GroupJavaQaTeamTest.java
- src/test/java/school/redrover/GroupLargusTest.java
- src/test/java/school/redrover/GroupSomeGroupTest.java
- src/test/java/school/redrover/NeedMoreCoffeeTestCase.java
- src/test/java/school/redrover/runner/BaseTest.java
> add changes to BaseTest

- src/test/java/school/redrover/GroupJasperAutomationTest.java
> Ignore test2

- src/test/java/school/redrover/GroupJasperAutomationTest.java
changed test name, driver to getDriver(), deleted  ChromeOptions, Thread.sleep(2000), driver.quit() according to the task
> change test

- src/test/java/school/redrover/ComradesAdelanteTest.java
- src/test/java/school/redrover/GroupJavaJitsuTest.java
Add simple test to the end of the group class
> Add simple test for learning

- src/test/java/school/redrover/NataChelovechikTest.java
add testVerifyOrthodonticsPresent()
> add class NataChelovechikTest

- src/test/java/school/redrover/old/NataChelovechikTest.java
add ignor remove class  NataChelovechikTest into folder 
old
> add ignor remove class  NataChelovechikTest into folder

- src/test/java/school/redrover/FooterTest.java
> Footer test

- src/test/java/school/redrover/GroupZeroBugTest.java
> Add class GroupZeroBugTest: method verifyNewJobCreated().

- src/test/java/school/redrover/PipelineTest.java
Reverts RedRoverSchool/JenkinsQA_06#930
> Revert "TestCreatePipelineWithoutParameters"

- src/test/java/school/redrover/NewItemTest.java
- src/test/java/school/redrover/PipelineTest.java
> testNewItemHeader

- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/SimpleTest.java
add test ерwhen check the name of a new noda
> testAddNewNode 

- src/test/java/school/redrover/NavigateToPeoplePageTest.java
added testNavigateToPeoplePage
> testNavigateToPeoplePage

- src/test/java/school/redrover/PipelineTest.java
[ADDED] TestCreatePipelineWithDescription
[ADDED] getWait method
> testCreatePipelineWithDescription

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
Add CreateMultiConfigurationProjectWithDescriptionTest to GroupHighwayToAqaTest
> Add first Jenkins test

- src/test/java/school/redrover/GroupZeroBugTest.java
> Refactor class GroupZeroBugTest, add method verifyJobBuild().

- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
> if the user presses CTRL+K cursor is active in search box

- src/test/java/school/redrover/PeoplePageTest.java
Create peoplePageTest, testViewPeoplePage(), verify header People page
Group99Bottles_NO
> testViewPeoplePage() 

- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
test EditDescriptionButtonChanges added
> test EditDescriptionButtonChanges added

- src/test/java/school/redrover/NeedMoreCoffeeTest.java
Add negative test for new item folder (special symbol dollar).
> AntoninaBozhok

- src/test/java/school/redrover/NeedMoreCoffeeTest.java
- src/test/java/school/redrover/PeoplePageTest.java
Create testViewIconButtonsPeoplePage(), create method ListText(List<WebElement> elementList)
Group99Bottles_NO
> testViewIconButtonsPeoplePage()

- src/test/java/school/redrover/GroupZeroBugTest.java
This test failed before. Smart Waits has been implemented. It works on the local machine. Please review.
> Add smartWaits, Remove @ignore of method verifyJobBuild().

- src/test/java/school/redrover/CatGroupTest.java
> SergePratasevich_TestCreateJob

- src/test/java/school/redrover/CatGroupTest.java
new test testVersionOfJenkins added
> new test added

- src/test/java/school/redrover/BestAutoTeamTest.java
- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/FuOpyatJavaTest.java
Just 1st test for Jenkins. Should work
> add BN's HeaderOfNewItem test 004

- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
test EditDescriptionButtonChanges refactored (xpath changed)
> test EditDescriptionButtonChanges refactored

- src/test/java/school/redrover/DreamTeamTest.java
- src/test/java/school/redrover/GroupDreamTeamTest.java
1. Add testErrorWhenCreatingJobWithEmptyName()
2. Add testOKButtonIsDisabledWhenCreatingJobWithEmptyName()
> Add empty project name tests

- src/test/java/school/redrover/BugsBustersGroupTest.java
- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
- src/test/java/school/redrover/PeoplePageTest.java
Create testAppearanceChangeDisappearanceSortArrowAppearsAfterPressingSortHeaderButton()
The test checks for the presence of a sort arrow on the sort button
After the first press, an arrow appears and points up
After the second press, the arrow points down
After pressing any other button, the sort arrow disappears from the sort button
> testSortArrowModeChangesAfterClickingSortHeaderButton()

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
> firstTestHeader

- src/test/java/school/redrover/BestAutoTeamTest.java
- src/test/java/school/redrover/old/BestAutoTeamTest.java
New test for new item creating was added
> add addNewItem test

- src/test/java/school/redrover/ManageJenkinsTest.java
added testErrorWhenCreateNewNodeWithEmptyName()
> Add test with empty new node name 

- src/test/java/school/redrover/CatGroupTest.java
- Added test for creation new log recorder
> Test for adding new log recorder

- src/test/java/school/redrover/ElNov686.java
> testVerifySearchBar 

- src/test/java/school/redrover/CatGroupTest.java
- src/test/java/school/redrover/runner/AndreiNevTest.java
> The first Jenkins test

- src/test/java/school/redrover/ComradesAdelanteGroupTest.java
The test verified that the title of the created job corresponds to the entered an item name.
> Add my first test for Jenkins

- src/test/java/school/redrover/GroupAndreyTest.java
add new test testProjectCreation
> add class GroupAndreyTest

- src/test/java/school/redrover/CreateFreestyleProjectTest.java
- src/test/java/school/redrover/NavigateToPeoplePageTest.java
1. refactored testNavigateToPeoplePage
2. added testCreateFreestyleProject
> testCreateFreestyleProject<galinasedunova>

- src/test/java/school/redrover/AndreiNevTest.java
move my test from the wrong directory
> move my test from the wrong directory

- src/test/java/school/redrover/GroupDreamTeamTest.java
Test testUserSidePanelMenu()  added
> Test User Side Panel Menu

- src/test/java/school/redrover/PipelineTest.java
[ADDED] testEditPipelineDescription
> Edit Pipeline Description

- src/test/java/school/redrover/CatGroupTest.java
add test sidePanel ("New Item", "People", "Build History", "Manage Jenkins", "My Views")
> testSidePanelNames

- src/test/java/school/redrover/MultibranchPipelineTest.java
add add class MultibranchPipelineTest
> AT - createMultibranchPipelineTest

- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
> fixed after ignore.dropdown

- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
>  ignore.delete

- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
add icon size tests on People tab
> add icon size tests on People tab 

- src/test/java/school/redrover/GroupJavaciraptorsTest.java
add second Jenkins test
fix Binoeder test names
> add second Jenkins test

- src/test/java/school/redrover/CaramelSyrupForJavaTest.java
add icon size changes on People tab test
> add icon size changes on People tab test

- src/test/java/school/redrover/MykolaTests.java
Tests for "New Item" function.
> Tests "New Item"

- src/test/java/school/redrover/GroupZeroBugTest.java
> Test case 02

- src/test/java/school/redrover/CreateTestsOnTheWelcomePage.java
Add new testNameTheFirstJob 
Add new class CreateTestsOnTheWelcomePage
> Add new testNameTheFirstJob

- src/test/java/school/redrover/BuildTaskOnWelcomePageTest.java
> fix: changed name of class to BuildTaskOnWelcomePageTest

- src/test/java/school/redrover/ComradesAdelanteGroupTest.java
> add my first test

- src/test/java/school/redrover/GroupZeroBugTest.java
Refactor code, removed faker in the new test
> Add new testRenameJobViaDropDownMenu(), make it simple

- src/test/java/school/redrover/HelloWorldGroupTest.java
Reverts RedRoverSchool/JenkinsQA_06#1225
> Revert "con"

- src/test/java/school/redrover/MultibranchPipelineTest.java
> test added

- src/test/java/school/redrover/GroupJavaExplorersTest.java
add testCreateNewItemWithSpecialCharactersInName and testCreateNewItemWithNullName
> add two negative tests

- src/test/java/school/redrover/AlexLeoGroupTests.java
added test Tasks Menu Navigation
> Added testTasksMenuNavigation

- src/test/java/school/redrover/NewItemTest.java
add testErrorWhenCreateNewItemWithSpecialCharacterName()
> testErrorWhenCreateNewItemWithSpecialCharacterName()

- src/test/java/school/redrover/AlexLeoGroupTests.java
- src/test/java/school/redrover/HeaderTest.java
- src/test/java/school/redrover/NewItemTest.java
Remove Description
Ignore my tests
> Ignore my classes

- src/test/java/school/redrover/GroupDreamTeamTest.java
rewrite testNewItem
add testProjectDisabled
> rewrite testNewItem, add testProjectDisabled

- src/test/java/school/redrover/GroupHighwayToAqaTest.java
- src/test/java/school/redrover/GroupZeroBugTest.java
> Add new test Create New Pipeline using scroll and select element from the list of elements.

- src/test/java/school/redrover/AlexLeoGroupTests.java
> Simple test

- src/test/java/school/redrover/TopMenuTest.java
testPreviewOfAddedDescriptionWhenClickUserIDButton() added.
> testPreviewOfAddedDescriptionWhenClickUserIDButton() added.

- src/test/java/school/redrover/BugsBustersGroupTest.java
- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/JasperGroupTest.java
https://trello.com/c/7IdSHEnE/111-tc-010706-item-freestyle-project-delete-project
>  Item > Freestyle Project > Delete project….

- src/test/java/school/redrover/CreateUsersTest.java
AT 15.01 | Users > Create Users > Verify that after user is created, User ID is displayed on the Users page
> AT 15.01 | Users > Create Users > Verify that after user is created, User ID is displayed on the Users page

- src/test/java/school/redrover/NewViewTest.java
US 11.01 https://trello.com/c/GxoNHLfP/126-us-1101-views-new-view-create-new-view
TC 11.01  https://trello.com/c/dGFyiGEy/144-tc-110101-views-new-view-create-new-view
AT 11.01 https://trello.com/c/WsOCvtZq/145-at-110101-views-new-view-create-new-view
> AT 11.01 Views > New View > Create New View

- src/test/java/school/redrover/BugsBustersGroupTest.java
- src/test/java/school/redrover/Folder2Test.java
AT -https://trello.com/c/tkfNhEu3
> Creates new Class Folder2Test, adds testFolderCreation

- src/test/java/school/redrover/CreatePipelineProjectTest.java
https://trello.com/c/R8ejp5QH/168-at-0002-pipeline-create-pipeline-project
> AT 00.02 Create Pipeline Project

- src/test/java/school/redrover/PipelineConfigureTest.java
> AT 02.04 | Pipeline > Configure > Set description

- src/test/java/school/redrover/CreatePipelineProjectTest.java
- src/test/java/school/redrover/HelloWorldGroupTest.java
https://trello.com/c/xt3mhIw6/172-at-0002-new-item-create-pipeline-project-created-project-is-present-on-dashboard
> AT 00.02 Created Project is present on Dashboard

- src/test/java/school/redrover/HelloWorldGroupTest.java
https://trello.com/c/ffBmZFzF
deleted useless  test
> HelloWorldGroupTest>testJenkinsVersion

- src/test/java/school/redrover/FreestyleProjectTest.java
RF - https://trello.com/c/IjOsm9JT/197-rf-freestyleprojecttesttestadddescriptiontofreestyleproject
> RF | FreestyleProjectTest>testAddDescriptionToFreestyleProject

- src/test/java/school/redrover/MultiConfigurationTest.java
https://trello.com/c/C36oBaIZ/199-at-0307-multi-configuration-project-rename-multi-configuration-project[
](https://trello.com/c/92L9hPwU/44-us-0307-multi-configuration-project-rename-multi-configuration-project)
> AT 03.07 | Multi-Configuration project > Rename Multi-Configuration project

- src/test/java/school/redrover/MultiConfigurTest.java
AT 00.03 |New Item > Multi Configuration project> Create Multi Configuration project
https://trello.com/c/GMQHlv7g
> AT 00.03 |New Item > Multi Configuration project> Create Multi Configuration project

- src/test/java/school/redrover/CreateMultiConfigurationProjectAddDescriptionTest.java
> US 03.01 | Multi-Configuration project > add description

- src/test/java/school/redrover/FolderTest2.java
> AT 04.01| New item > Folder > Create Folder

- src/test/java/school/redrover/PipelineConfigureTest.java
> AT 02.04 | Pipeline > Configure > Set discarding of old builds 

- src/test/java/school/redrover/TestCreateDuplicatePipeline.java
…> Create Pipeline Project with the same name as another project"
> Added test related to "AT 00.02 | New Item > Create Pipeline Project > Create Pipeline Project with the same name as another project"

- src/test/java/school/redrover/FolderTest2.java
> AT 04.02| New item > Folder > Create and Rename Folder

- src/test/java/school/redrover/FolderTest2.java
- src/test/java/school/redrover/MyViewsTest.java
- src/test/java/school/redrover/PipelineTest2.java
> AT 00.02| New Item > Create Pipeline Project

- src/test/java/school/redrover/DeletePipelineTest.java
Add additional steps to go back on the dashboard and go to the project page
> RF | 02.05 | Pipeline > Delete Pipeline by the left sidebar delete button

- src/test/java/school/redrover/FolderTest4.java
- src/test/java/school/redrover/HelloWorldGroupTest.java
> AT 04.01 | New item > Folder > Create Folder

- src/test/java/school/redrover/RestApiLinkTest.java
> AT 13.02 | Footer > REST API

- src/test/java/school/redrover/HeaderTest.java
> AT 17.01 | Page-header > Logo > Return to the dashboard page

- src/test/java/school/redrover/NewItemTest.java
The first commit 
AT 00.02 https://trello.com/c/6roVwwZI/253-at-0002-new-item-pipeline-project-create-pipeline-project
TC 00.02 https://trello.com/c/KDdckLb6/214-tc-0002-new-item-create-pipeline-project
The second commit
AT 00.02 https://trello.com/c/TpYRKE4c/256-at-0002-new-item-pipeline-project-create-pipeline-project-with-invalid-name
TC 00.02 https://trello.com/c/rznROacd/216-tc-0002-new-item-pipeline-project-create-pipeline-project-with-invalid-name
> add createPipelineProjectTest()

- src/test/java/school/redrover/FooterJenkinsVersionTest.java
> AT 13.01 | Footer > Jenkins version

- src/test/java/school/redrover/NewViewTest.java
https://trello.com/c/g9fxcllm/318-at-1101-views-create-new-view[
](https://trello.com/c/GxoNHLfP/126-us-1101-views-new-view-create-new-view)
> AT 11.01 Views | Create New View > added testCreateNewViewSecond

- src/test/java/school/redrover/RenamePipelineTest.java
> AT 02.07 | Pipeline > Rename the existing pipeline project

- src/test/java/school/redrover/MainPage.java
- src/test/java/school/redrover/MainTest.java
- src/test/java/school/redrover/base_abstract/BasePage.java
> AT 00.01|[MainPage][CreateAJob][MultibranchPipeline]

- src/test/java/school/redrover/NewItemUS0001Test.java
AT - https://trello.com/c/7V8x0u5y/312-at-0002-new-item-pipeline-project-create-pipeline-project-with-the-same-name
TC - https://trello.com/c/WR19qLXy/215-tc-0002-new-item-pipeline-project-create-pipeline-project-with-the-same-name
rename class NewItemTest -> NewItemUS0001Test
> add createPipelineProjectSameNamedTest()

- src/test/java/school/redrover/PipelineConfigureTest.java
pipeline is created and disabled
AT - https://trello.com/c/eKyBNjGG
TC - https://trello.com/c/F1DcidMp
> AT 02.04 | Pipeline > Configure > Disable a pipeline during creation

- src/test/java/school/redrover/MultiConfigurTest.java
> AT 03.01 | Multi-Configuration project > add description

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/NeedMoreCoffeeTest.java
https://trello.com/c/HMevpa4X/329-at-1301-footer-check-jenkins-version-on-footer-in-people-page
> AT 13.01 | Footer > Check Jenkins version on Footer in People page

- src/test/java/school/redrover/MultiConfigurTest.java
> AT 00.03 | New Item > Multi Configuration project > Create Multi Configuration project with space instead name

- src/test/java/school/redrover/CreatePipelineProject3Test.java
> AT 00.02 add create pipeline test

- src/test/java/school/redrover/NewViewTest.java
https://trello.com/c/n0QDhaE0/370-at-1102-views-new-view-rename-view
> TC 11.02 | Views > New View > Rename view

- src/test/java/school/redrover/MultiConfigurTest.java
> AT  00.03| New Item > Multi Configuration project> Create Multi Configuration project with special symbols in name

- src/test/java/school/redrover/runner/FooterTest2.java
> AT 13.01 | Footer > Verify Jenkins version on Manage Jenkins page

- src/test/java/school/redrover/FooterTest2.java
> RF | Move the FooterTest2 class to the correct package

- src/test/java/school/redrover/FooterJenkinsVersionTest.java
https://trello.com/c/w7lhqUsD - AT 13.01 | Footer > Verify Jenkins version on Nodes Page
https://trello.com/c/F8j6nS8B - AT 13.01 | Footer > Verify clicking on Jenkins version opens site on Nodes Page
> AT 13.01 | Footer > Verify Jenkins version on Nodes Page

- src/test/java/school/redrover/Folder2Test.java
RF - https://trello.com/c/Fu3mTWSB
Locators are placed before tests. method createAFolder added . testFolderCreation() refactored
> RF 04.01 | New Item > Folder >Create folder

- src/test/java/school/redrover/FooterTest2.java
> AT 13.02 | Footer > Verify REST API link

- src/test/java/school/redrover/NewViewTest.java
https://trello.com/c/FkhYdl4m/393-at-1104-views-delete-view
> TC 11.04 |Views > Delete view

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/WOLyU5O7/422-at-0001-new-item-freestyle-project-create-freestyle-project-using-valid-name
> add testCreateFreestyleProjectWithValidName

- src/test/java/school/redrover/CreatePipelineProject4Test.java
https://trello.com/c/eQfKibOA/395-at-0002-new-item-create-pipeline-project
> AT 00.02 | New Item >Create Pipeline Project

- src/test/java/school/redrover/GroupZeroBugTest.java
- src/test/java/school/redrover/ManageUsersTest.java
https://trello.com/c/I67arwly/439-at-0903-manage-jenkins-manage-users-delete-user
> AT 09.03 | Manage Jenkins > Manage Users > Delete User

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/o97eAfzB/471-at-0002-new-item-create-pipeline-project
> AT 00.02 | New Item > Create Pipeline Project

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/GroupDreamTeamTest.java
- src/test/java/school/redrover/TopMenuTest.java
https://trello.com/c/Hdgl34VL/473-rf-move-testnewfreestyleprojectcreated-to-freestyleprojecttest
Move testNewFreestyleProjectCreated()
from GroupDreamTeamTest
to FreestyleProjectTest
Ignore https://trello.com/c/ESKh93Cp/475-err-topmenutest-testpreviewofaddeddescriptionwhenclickuseridbutton
> RF | Move testNewFreestyleProjectCreated() to FreestyleProjectTest

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/GroupDreamTeamTest.java
RF - https://trello.com/c/OhXAiD1p/485-rf-move-testerrorwhencreatingfreestyleprojectwithemptyname-to-freestyleprojecttest
Move testErrorWhenCreatingFreeStyleProjectWithEmptyName()
from GroupDreamTeamTest
to FreestyleProjectTest
> RF | Move testErrorWhenCreatingFreeStyleProjectWithEmptyName() to FreestyleProjectTest

- src/test/java/school/redrover/FreestyleProjectTest.java
- src/test/java/school/redrover/GroupDreamTeamTest.java
RF - https://trello.com/c/Pz0du9d7/488-rf-move-testokbuttonisdisabledwhencreatingfreestyleprojectwithemptyname-to-freestyleprojecttest
Move testOKButtonIsDisabledWhenCreatingFreestyleProjectWithEmptyName
from GroupDreamTeamTest
to FreestyleProjectTest
> RF | Move testOKButtonIsDisabled to FreestyleProjectTest

- src/test/java/school/redrover/CreateUserTest.java
> AT 09.01 add create user test

- src/test/java/school/redrover/AlexLeoGroupTests.java
- src/test/java/school/redrover/HeaderTest.java
- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/UserPageTest.java
RF - https://trello.com/c/zs9kMccD/490-rf-move-tests
Move tests from AlexLeoGroupTests
> RF | Move tests

- src/test/java/school/redrover/MultiConfigurationTest.java
[ER] - https://trello.com/c/Ujs29VWl/499-err-multiconfigurationrenametest-testrenamemulticonfigurationprojectfromdashboard
deleted one locator
> testRenameMultiConfigurationProjectFromDashboard

- src/test/java/school/redrover/DeletePipelineTest.java
> AT 02.05 | Pipeline > Delete Pipeline by the drop-down menu to the project page

- src/test/java/school/redrover/CreateMultiConfigurationProjectTest.java
AT - https://trello.com/c/b6B7qYkF/463-at-0408-new-item-folder-create-multiconfiguration-project-in-folder 
TC - https://trello.com/c/wilWZVse/462-tc-0408-new-item-folder-create-multiconfiguration-project-in-folder
> AT 04.08 | New item > Folder > Create Multiconfiguration project in Folder

- src/test/java/school/redrover/MultiConfigurTest.java
> AT 00.03| New Item > Multi Configuration project> Create Multi Configuration project with equal name

- src/test/java/school/redrover/DeleteFreestyleProjectTest.java
https://trello.com/c/rXJjrhjq/465-at-0107-freestyle-project-delete-project
> AT 01.07 | Freestyle project > Delete project

- src/test/java/school/redrover/CreateUserTest.java
> AT 09.01 | Manage Jenkins > Manage Users > Create User

- src/test/java/school/redrover/MultiConfigurationTest.java
https://trello.com/c/7yRoRRTO/548-at-0302-multi-configuration-disable-multi-configuration-project-create-multi-configuration-project-with-status-disable
> AT 03.02 | Multi Configuration> Disable Multi Configuration Project > Create Multi Configuration Project with status Disable 

- src/test/java/school/redrover/PipelineConfigureTest.java
AT - https://trello.com/c/YUEPgqMu/540-at-0204-tc-0204-pipeline-configure-add-description
TC - https://trello.com/c/TrFPGUy7/330-tc-0204-pipeline-configure-add-description
> AT 02.04 | Pipeline > Configure > Add description

- src/test/java/school/redrover/UserTest.java
https://trello.com/c/DEGQsIo7/445-at-0901-manage-jenkins-manage-users-create-user
> AT 09.01 Manage Jenkins > Manage Users > Create User

- src/test/java/school/redrover/CreateFreestyleProjectTest.java
> AT 00.01 | New Item > Freestyle Project > Create Freestyle Project with invalid name

- src/test/java/school/redrover/CreateFreestyleProjectJobTest.java
[TC](https://trello.com/c/JnNUNjss/186-tc-0001-new-item-freestyle-project-create-freestyle-project)
[AT](https://trello.com/c/U8A0Wz4t/222-at-0001-new-item-freestyle-project-create-freestyle-project)
> testCreateFreestyleProjectJoband

- src/test/java/school/redrover/CreateFreestyleProject1Test.java
- src/test/java/school/redrover/JavaNiSyGroupTest.java
> AT 00.01 | New Item > Freestyle Project > Create Freestyle Project

- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/NewItemTest.java
https://trello.com/c/94QDaDy0/572-at-0005-new-item-create-multibranch-pipeline[
](https://trello.com/c/npokns9Y/571-us-0005-new-item-create-multibranch-pipeline)
> AT 00.05 New Item > Create Multibranch pipeline

- src/test/java/school/redrover/JenkinsVersionTest.java
https://trello.com/c/ltDZH2i8
https://trello.com/c/1iHxZgT3
https://trello.com/c/2HKsM0pi
https://trello.com/c/3JiUdfW4
https://trello.com/c/5wrPAdTd
> AT 13.01 | Footer > Verify Jenkins version | add 5 tests

- src/test/java/school/redrover/CreateMultiConfigurationProject1Test.java
>  AT 03.01 | Multi-Configuration project > add description

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/hHXjPWqk/612-at-0002-new-item-create-pipeline-project-with-correct-name
> AT 00.02| New Item > Create Pipeline Project with correct name

- src/test/java/school/redrover/CreatePipelineProject5Test.java
https://trello.com/c/U8IHZ44a/611-at-0002-new-item-create-pipeline-project
> AT 00.02 | Create Pipeline Project TC

- src/test/java/school/redrover/NeedMoreCoffeeTest.java
- src/test/java/school/redrover/PipelineProject1_Test.java
Add new class PipelineProject1_Test and delete it in NeedMoreCoffeeTest
> AT 00.02| New Item > Create Pipeline Project 

- src/test/java/school/redrover/Folder2Test.java
AT -https://trello.com/c/8TLFRdYD
> AT 04.01| New item > Folder >Create folder> Create two folders

- src/test/java/school/redrover/ManageJenkinsTest.java
[RF](https://trello.com/c/9te9NRd6)
> RF 09.02 | Manage Jenkins > Search settings > Search with numeric symbol

- src/test/java/school/redrover/PipelineConfigureTest.java
RF - https://trello.com/c/bXzp2zPs
correct a waiter expectedConditions, improve configurePipeline locator, change Assert
> RF 02.04 | Pipeline > Configure > Disable a pipeline during creation

- src/test/java/school/redrover/PipelineConfigureTest.java
AT - https://trello.com/c/CJ8Og32v/544-tc-0204-pipeline-configure-disable-project
TC - https://trello.com/c/xjIsNhLi/317-tc-0204-pipeline-configure-disable-project
> AT 02.04 | Pipeline > Configure > Disable Project

- src/test/java/school/redrover/NewItemTest.java
https://trello.com/c/LKWEkgRy
Add testCreatePipelineGoingFromManageJenkinsPage()
> AT 00.02 | New Item > Create Pipeline Project > Create Pipeline Going From Manage Jenkins Page

- src/test/java/school/redrover/GroupJavaExplorersTest.java
- src/test/java/school/redrover/NewItem2Test.java
https://trello.com/c/yJe0wLP9/645-at-0005-new-item-create-multibranch-pipeline-without-description
> AT 00.05 | New Item > Create Multibranch Pipeline without description

- src/test/java/school/redrover/MultibranchPipeline2Test.java
https://trello.com/c/OJE8MXhK/668-at-0501-multibranch-pipeline-create-multibranch-pipeline-with-description[
](https://trello.com/c/FE9v1AQC/288-us-0501-multibranch-pipeline-create-multibranch-pipeline)
> AT 05.01 | Multibranch Pipeline > Create Multibranch Pipeline with Description

- src/test/java/school/redrover/DeletePipeline1Test.java
> AT 02.05 add delete pipeline test

- src/test/java/school/redrover/UserTest.java
https://trello.com/c/4lkYXU0b/656-at-1505-users-user-id-delete-user-via-bin-button
> AT 15.05 | Users > User ID > Delete user via "Bin" button

- src/test/java/school/redrover/CreateUserTest.java
- src/test/java/school/redrover/FreestyleProjRenameTest.java
AT - https://trello.com/c/13Ww0W6N
TC - https://trello.com/c/0N0nuGa3
> AT 01.06 | Freestyle project > Rename project from the freestyle project page

- src/test/java/school/redrover/MultibranchPipeline2Test.java
https://trello.com/c/wr2MIwDo/700-at-0502-multibranch-pipeline-rename-multibranch-pipeline[
](https://trello.com/c/LjXiefLV/293-us-0502-multibranch-pipeline-rename-multibranch-pipeline)
> AT 05.02 | Multibranch Pipeline > Rename Multibranch pipeline

- src/test/java/school/redrover/ManageSearchTest.java
Check search by single letter
https://trello.com/c/S8N7Axgu
> AT 09.02 | Manage Jenkins > Search settings

- src/test/java/school/redrover/CreateMultiConfigurationProject2Test.java
https://trello.com/c/N6eEXSJv/724-at-0003-new-item-multi-configuration-project-create-multi-%D1%81onfiguration-project
> AT 00.03 | New Item > Multi_Configuration

- src/test/java/school/redrover/HeaderTest.java
https://trello.com/c/2u9zVo7k/673-at-1703-page-header-notification-and-security-icons-to-receive-alerts-from-jenkins
> AT 17.03 | Page-header > Notification and Security icons

- src/test/java/school/redrover/GroupJavaExplorersTest.java
- src/test/java/school/redrover/NewItem2Test.java
https://trello.com/c/ffsLIHY7/695-at-0005-new-item-create-multibranch-pipeline-with-null-name
https://trello.com/c/SmK1qikZ/729-rf-0005-new-item-create-multibranch-pipeline-without-description
> AT 00.05 | New Item > Create Multibranch Pipeline with Null Name

- src/test/java/school/redrover/PreviewDescriptionTest.java
- src/test/java/school/redrover/ProjectDescriptionTest.java
https://trello.com/c/HlNzk7rk/736-at-010501-freestyle-project-preview-description
> AT 01.05.01 | Freestyle project > Preview description

- src/test/java/school/redrover/MultiConfigurTest.java
> 03.02 | Multi-Configuration > Check on Dashboard that project is disabled

- src/test/java/school/redrover/JasperGroupTest.java
https://trello.com/c/6JXdCBZU/707-rf-0000-delete-jaspergrouptesttestvalidationmessage
> RF 00.00 Delete JasperGroupTest.testValidationMessage

- src/test/java/school/redrover/FreestyleProject3Test.java
- src/test/java/school/redrover/NewProject3Test.java
https://trello.com/c/qReY4zqv/796-rf-moving-tests-into-one-class
> RF | moving tests into one class

- src/test/java/school/redrover/Pipeline2Test.java
AT- https://trello.com/c/YsBpyP25
> AT 02.05 | Pipeline > Delete Pipeline> Delete Pipeline from dashboard

- src/test/java/school/redrover/NewItemTest.java
- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/QFU04bNm/806-at-0201-pipelineview-pipeline-pagerename-and-delete-pipeline
> AT 02.01 | Pipeline>View pipeline page>rename and delete

- src/test/java/school/redrover/Folder2Test.java
AT - https://trello.com/c/bjp0VxAw
> AT 00.04 | New Item > Folder >Create folders using allowed characters

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/AI2jrhkg/837-rf-0000-refactoring
> RF | Pipeline test

- src/test/java/school/redrover/NewItem2Test.java
add _testCreateFolder()_
AT: https://trello.com/c/yjoiVzdQ
TC: https://trello.com/c/QN9xdX3D
> AT 00.04 | New item > Folder > Create folder without description

- src/test/java/school/redrover/Folder4Test.java
> TC 00.04| New item > Create Folder

- src/test/java/school/redrover/PeoplePageTest.java
> AT 07.01 | People > User ID > Managing Users > Find user from the Search box on the header of page

- src/test/java/school/redrover/MultiConfiguration3Test.java
> RF MultiConfiguration3Test>testCreateMultiConfigurationProjectWithSpecialSymbols

- src/test/java/school/redrover/NewViewTest.java
RF https://trello.com/c/Sg8pK0Dv/862-rf-refactor-test-createnewview-and-method
> Refactor test CreateNewView and method

- src/test/java/school/redrover/Folder4Test.java
> RF 00.04| Item > Create Folder without description

- src/test/java/school/redrover/HeaderTest.java
https://trello.com/c/PcMvXX2F/865-at-1704-page-header-open-configure-from-dropdown-menu
> AT 17.04 | Page-header > Open "Configure" from dropdown menu

- src/test/java/school/redrover/ManageUsers2Test.java
> Add ManageUser2Test

- src/test/java/school/redrover/PipelineProjectTest.java
> Refactor tests

- src/test/java/school/redrover/CreateFreestyleProjectTest.java
AT https://trello.com/c/xRXMLlLg/869-at-0001-new-item-freestyle-project-create-freestyle-project-with-valid-data
TC https://trello.com/c/2rn2546i/867-tc-0001-new-item-freestyle-project-create-freestyle-project
> AT 00.01 | > Freestyle Project > Create Freestyle Project with valid data

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/ThAemx5Q/744-at-0107-freestyle-project-delete-project-from-the-dashboard-list
> AT 01.07 | Freestyle project > Delete project from the dashboard list

- src/test/java/school/redrover/FreestyleProject4Test.java
> AT 00.00 | New Item > Freestyle Project > Create Freestyle Project

- src/test/java/school/redrover/ConfigureFolderTest.java
AT 04.04 | Folder> Configure Folder
https://trello.com/c/TeAmPFId
> US 04.04 | Folder > Configure Folder

- src/test/java/school/redrover/MultiConfigurationTest.java
> AT 03.02 | Multi-Configuration > Disable a multi-configuration project

- src/test/java/school/redrover/UserProfileTest.java
RF - https://trello.com/c/rBpasxCN
refactoring AT test, removing constants, optimizing the test 
AT 09.05 | Dashboard > Manage Jenkins > Manage Users > Change the user profile > Add description to User on the User Profile page
> RF 09.05 | Dashboard > Change the user profile > Add description to User Profile 

- src/test/java/school/redrover/MultibranchPipeline3Test.java
> AT 04.15 | Folder > Move Multibranch Pipeline to Folder

- src/test/java/school/redrover/NewItem2Test.java
AT - https://trello.com/c/TlGhjvzA
> AT 00.00 New Item > Create all types items using a DataProvider

- src/test/java/school/redrover/CustomizeUserSettingsTest.java
US - https://trello.com/c/dAOqepaW/504-tc-0905-dashboard-manage-jenkins-manage-users-change-the-user-profile-update-user-name-on-the-user-profile-page
TC - https://trello.com/c/dAOqepaW/504-tc-0905-dashboard-manage-jenkins-manage-users-change-the-user-profile-update-user-name-on-the-user-profile-page
> Update User Name On The User Profile Page

- src/test/java/school/redrover/UserProfileTest.java
AT - https://trello.com/c/EcucUgqa
TC - https://trello.com/c/M2V5QqM1
> AT 09.05 | Dashboard > Change the user profile > Update description for User

- src/test/java/school/redrover/ConfigureFolderTest.java
https://trello.com/c/22xJylhL
Reduced the amount of Code.
> RF 04.04 | Folder> Configure Folder>Configure Display Name, Description, Health Metrics

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/FYYiKJbQ/934-at-010701-freestyle-project-delete-project-from-the-project-page
> AT 01.07.01 | Delete project from the project page

- src/test/java/school/redrover/CreateMultiConfigurationProjectTest.java
- src/test/java/school/redrover/FooterJenkinsVersionTest.java
- src/test/java/school/redrover/MultiConfiguration2Test.java
- src/test/java/school/redrover/MultiConfigurationProject1Test.java
- src/test/java/school/redrover/MultibranchPipeline2Test.java
- src/test/java/school/redrover/MultibranchPipelineTest.java
- src/test/java/school/redrover/MyViewsTest.java
- src/test/java/school/redrover/TopMenuTest.java
- src/test/java/school/redrover/UserTest.java
> RF Multi-Configuration project > add description

- src/test/java/school/redrover/Folder4Test.java
> AT 04.01 | Create New View in Folder

- src/test/java/school/redrover/HeaderTest.java
> AT 17.04.01 | Dashboard > Make sure admin page is available

- src/test/java/school/redrover/Folder4Test.java
> AT 04.02| Rename created Folder

- src/test/java/school/redrover/MultiConfigurationTest.java
[RF] - https://trello.com/c/ZCxkSJV3/944-rf-0307-new-item-multi-configuration-project-rename-multi-configuration-project
refactored testRenameMultiConfigurationProjectFromDashboard
> RF 03.07 | Rename Multi-Configuration project

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/B3xl4nJE/945-at-0106-freestyle-project-renaming-a-project-from-the-dashboard-list
> AT 01.06_Renaming a project from the dashboard list

- src/test/java/school/redrover/Folder2Test.java
AT - https://trello.com/c/dbYgxCeD
> AT 04.04 | Folder > Configure Folder > Configure folder with description

- src/test/java/school/redrover/CreateMultibranchPipeline1Test.java
https://trello.com/c/QMIHG561/949-at-0005-mainpagecreateajobmultibranchpipeline-createmultibranchpipelinetest-maksim-2404
> AT 00.05|[MainPage][CreateAJob][MultibranchPipeline] <Maksim2404>

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/w4zAg3Bd/950-rf-0105-freestyle-project-description
> RF 01.05 | Freestyle project >  description

- src/test/java/school/redrover/FreestyleProject3Test.java
https://trello.com/c/WryoZYY2/959-at-010601-freestyle-project-renaming-a-project-from-the-project-page
> AT 01.06.01 | Freestyle project > Renaming a project from the project page

- src/test/java/school/redrover/PipelineProjectTest.java
> AT 02.04 | Pipeline > Configure > Set description to existing pipeline

- src/test/java/school/redrover/PipelineProject2Test.java
Added testRenamePipelineProject and renamed class. Link to AT in Trello: https://trello.com/c/OIbQuvxN/963-at-0002-new-item-create-pipeline-project-rename-project
> Sh create new pipeline project test

- src/test/java/school/redrover/ManageJenkinsTest.java
> AT 09.02 | Manage Jenkins | Search for Settings by Keyword

- src/test/java/school/redrover/CreateFolderTest.java
- src/test/java/school/redrover/CreateFreestyleProjectTest.java
- src/test/java/school/redrover/FreestyleProject1Test.java
- src/test/java/school/redrover/NewItem2Test.java
- src/test/java/school/redrover/NewViewTest.java
- src/test/java/school/redrover/Pipeline2Test.java
ERR- https://trello.com/c/VcvlSrlt
Ignore 8 tests total
> Ignore tests

- src/test/java/school/redrover/PipelineTest.java
> AT 00.02 | New Item > Create a basic Pipeline through the Jenkins classic UI

- src/test/java/school/redrover/Pipeline2Test.java
RF - https://trello.com/c/AemAD603
Add a waiter for alert, change some locators
> RF 02.05 | Pipeline > Delete Pipeline > Delete Pipeline from dashboard

- src/test/java/school/redrover/Footer2Test.java
https://trello.com/c/QNH0q02r/713-at-1302-footer-rest-api-find-a-link-to-rest-api
> AT 13.02| Footer > REST API > Find a link to REST API

- src/test/java/school/redrover/NewItemTest.java
- src/test/java/school/redrover/PipelineProjectTest.java
https://trello.com/c/i2zgU75T
Move testCreatePipelineGoingFromManageJenkinsPage() from NewItemTest to PipelineProjectTest
> RF 00.02 | New Item > Create Pipeline Project > Create Pipeline Going From Manage Jenkins Page

- src/test/java/school/redrover/Folder2Test.java
AT - https://trello.com/c/Urw23wH5
Moving some variables before tests
Ignore testTwoFoldersCreation()
> AT 00.04 | New Item > Create folder from existing folder

- src/test/java/school/redrover/NewItem2Test.java
https://trello.com/c/s7QudAap/979-rf-0005-new-item-create-multibranch-pipeline-without-description
> RF 00.05 | New Item > Create Multibranch Pipeline without description

- src/test/java/school/redrover/NewItemFreestyleProjectAllTest.java
> AT 00.01 | New Item>Freestyle Project>Create Freestyle Project with valid data

- src/test/java/school/redrover/FolderTest.java
> AT 00.04| New item > Create Folder with an existing name

- src/test/java/school/redrover/Folder2Test.java
RF - https://trello.com/c/k5PLPwCT
refactor createAFolder method and using it tests
> RF 04.00 | Folder > Create a new folder

- src/test/java/school/redrover/NewItem2Test.java
> AT 04.00| Folder > Create folder using invalid data

- src/test/java/school/redrover/SearchTest.java
https://trello.com/c/1N63EcVU/1017-at-0902-manage-jenkins-search-settings-test-search-box-is-insensitive
> AT 09.02 | Manage Jenkins >  test Search Box is Insensitivity

- src/test/java/school/redrover/MyViewsTest.java
AT - https://trello.com/c/iONBrkOt/181-at-1504-user-user-id-my-viewscreate-my-view
TC - https://trello.com/c/Yfc7kPaB/180-tc-1504-user-user-id-my-viewscreate-my-view
> AT 15.04 | User > User ID > My Views > Create My View

- src/test/java/school/redrover/FreestyleProject5Test.java
https://trello.com/c/Fp4VDlTy   АТ 00.01 | Item > New Item > Freestyle Project > Create Freestyle Project
> АТ 00.01 | Item > New Item > Freestyle Project > Create Freestyle Project

- src/test/java/school/redrover/Folder4Test.java
> RF 00.00 | Fix the locators

- src/test/java/school/redrover/CreateFreestyleProject2aTest.java
https://trello.com/c/UwoDl78l/866-at-0001-create-freestyle-project
> AT 00.01 | Create Freestyle Project

- src/test/java/school/redrover/HeaderTest.java
AT 17.03 | Page-header > Notification and Security icons > Icon Color Change
https://trello.com/c/ANDinfw8
> AT 17.03 | Page-header > Notification and Security icons > Icon Color Change

- src/test/java/school/redrover/FreestyleProject5Test.java
https://trello.com/c/FBcpxVz1    AT 01.01 | Freestyle project > Disable the project from this page
> AT 01.01 | Freestyle project > Disable the project from this page

- src/test/java/school/redrover/FreestyleProject5Test.java
https://trello.com/c/ZkP6QfPO   RF 01.01 | Freestyle project > Disable the project from this page
> RF 01.01 | Freestyle project > Disable the project from this page

- src/test/java/school/redrover/ProjectFolder2Test.java
RF - https://trello.com/c/nAh0PVqX
rename Folder2Test to ProjectFolder2Test
> RF | Refactor class name

- src/test/java/school/redrover/MultiConfigurationProject2Test.java
> AT 00.03 | New Item > Multi - Configuration project >Create Multi-Сonfiguration project

- src/test/java/school/redrover/FreestyleProject4Test.java
> AT 01.01 | Freestyle project > View project page > Disable the project from this page

- src/test/java/school/redrover/FolderTest.java
RF: https://trello.com/c/kYPtB0ts/972-rf-create-folder-method
refactored folder tests
> RF FolderTest class

- src/test/java/school/redrover/HeaderTest.java
https://trello.com/c/5YHSvg4w/1052-rf-1704-page-header-open-builds-and-configure-from-dropdown-menu
> RF 17.04 | Page-header > Open "Builds" and "Configure" from dropdown menu

- src/test/java/school/redrover/Folder4Test.java
> AT 04.03 | Folder > Move Folder to Folder

- src/test/java/school/redrover/Folder5Test.java
> AT 04.02 | Folder > Rename Folder

- src/test/java/school/redrover/ManageUsersTest.java
https://trello.com/c/tPPffDvW/1067-at-1501-users-create-users-in-the-users-table
> AT 15.01 | Users > Create users in the Users table

- src/test/java/school/redrover/MultiConfiguration3Test.java
> RF 03.01 | Multi-Configuration project > add description

- src/test/java/school/redrover/PipelineTest.java
> RF 02.01 | Pipeline>View pipeline page>Rename

- src/test/java/school/redrover/CreateFolderTest.java
> RF 04.00 | Folder > Create Folder

- src/test/java/school/redrover/MultiConfiguration3Test.java
> RF  00.03| New Item > Multi Configuration project> Create Multi Configuration project with equal name

- src/test/java/school/redrover/HeaderTest.java
https://trello.com/c/eApbKfIS/1060-at-tc-1704-page-header-open-my-views-and-credentials-from-dropdown-menu
added Xpaths to an already existing DataProvider to check two more tabs from admin Dropdown Menu
> AT TC 17.04 | Page-header > Open "My views" and "Credentials" from dropdown menu

- src/test/java/school/redrover/PipelineProject4Test.java
https://trello.com/c/XYizQpCN
add new class for my tests
add test testCreateNewPipelineProject
> AT 00.02| New Item > Create New Pipeline Project

- src/test/java/school/redrover/MultiConfiguration3Test.java
> RF 03.07 | Multi-Configuration project > Rename Multi-Configuration project

- src/test/java/school/redrover/Pipeline2Test.java
https://trello.com/c/ewI7MB75/1057-rf-0000-fix-ignored-test
> RF 00.00 | Fix ignored test

- src/test/java/school/redrover/CreateFolderTest.java
https://trello.com/c/eMKnXyJD/1037-rf-0400-folder-create-folder
Добавила wait на кнопку сохранить
> RF 04.00 | Folder > Create Folder>Fix ignored test

- src/test/java/school/redrover/PipelineProject2Test.java
Trello:   [AT 00.02 | New Item > Create Pipeline Project > Disable Project](https://trello.com/c/OIbQuvxN/963-at-0002-new-item-create-pipeline-project-disable-project)
> Added testDisableProject

- src/test/java/school/redrover/User2Test.java
- src/test/java/school/redrover/User3Test.java
create User3Test class
add testInputInfoIntoDescription()
add addDescriptionToFirstUser method for testInputInfoIntoDescription()
AT: https://trello.com/c/lBpZNWr0
TC: https://trello.com/c/XhjQ8crp
> AT 15.03 | Users > User ID > Configure > Input into description field

- src/test/java/school/redrover/CreateNewOrganizationFolderTest.java
> AT 00.06 | New Item > Organization Folder > Create new Organization Folder with existing name

- src/test/java/school/redrover/ProfileTest.java
> RF 17.04 | Page-header > User Profile Icon > User's profile icon and dropdown menu

- src/test/java/school/redrover/CreateFolder3Test.java
AT https://trello.com/c/WWfp2qPb
US https://trello.com/c/yWxg1qXt
> AT 04.05 | Folder > Delete Folder (delete the unnecessary folder and keep other)

- src/test/java/school/redrover/MultibranchPipeline3Test.java
- src/test/java/school/redrover/NewItem2Test.java
https://trello.com/c/GrgoJfrV/1120-rf-0005-multibranch-pipeline-relocate
> RF Multibranch Pipeline > Create Multibranch Pipeline without description

- src/test/java/school/redrover/Footer2Test.java
> AT 13.01  Footer > Jenkins version >Open the Jenkins site 

- src/test/java/school/redrover/MultibranchPipeline3Test.java
- src/test/java/school/redrover/NewItem2Test.java
https://trello.com/c/kaasiL29/1119-rf-0005-multibranch-pipeline-create-multibranch-pipeline-with-null-name
> RF 00.05 | Multibranch Pipeline > Create Multibranch Pipeline with Null Name

- src/test/java/school/redrover/PipelineProject4Test.java
> AT 02.07 | Pipeline > Rename from Pipeline page

- src/test/java/school/redrover/PipelineTest.java
Add new test + refactoring
https://trello.com/c/0gqzxAHj/1126-at-tc-0201-pipelineview-pipeline-pageopen-created-pipeline
> AT TC 02.01 | Pipeline>View pipeline page>open created Pipeline

- src/test/java/school/redrover/MultiConfigurationProject3Test.java
> AT 00.03 | New Item > Multi - Configuration project >Create Multi-Сonfiguration project (Negative)

- src/test/java/school/redrover/Pipeline26Test.java
> AT 00.02| New Item > add Create Pipeline Project test

- src/test/java/school/redrover/MultiConfigurationProject3Test.java
> RF 00.03 | New Item > Multi - Configuration project >Create Multi-Configuration project (Negative)

- src/test/java/school/redrover/BuildHistoryPageTest.java
AT - https://trello.com/c/uboKuQFw
TC - https://trello.com/c/xp2NwhQb
US - https://trello.com/c/OM8dEDOm
> AT 08.03 | Build History> History of one build > Description for Build is added

- src/test/java/school/redrover/Folder1Test.java
- src/test/java/school/redrover/FreestyleProject1Test.java
- src/test/java/school/redrover/Pipeline5Test.java
> RF 00.01 | New Item > Freestyle Project > Create Freestyle Project

- src/test/java/school/redrover/MultiConfigProject26Test.java
> AT 00.03 | New Item > Multi-Configuration project > Add test creating Multi-Сonfiguration project

- src/test/java/school/redrover/PipelineProject6Test.java
> RF 00.02 | Pipeline Project > Restore previously deleted class and tests

- src/test/java/school/redrover/FreestyleProject11Test.java
https://trello.com/c/OIbGHSGC/880-at-0001-new-item-freestyle-project-create-freestyle-project
> AT 00.01 New Item>Freestyle Project>Create Freestyle Project

- src/test/java/school/redrover/NewViewTest.java
added testCreateNewViewWithJobFilters
AT: https://trello.com/c/PFWRYxhM/1065-at-1101-views-new-view-create-new-view-create-new-view-with-job-filters
> AT 11.01 | Views > New View > Create New View > Create New View with Job filters

- src/test/java/school/redrover/PipelineTest.java
https://trello.com/c/329FLKci/721-at-0205-pipeline-delete-pipeline-from-drop-down-menu
> AT 02.05 | Pipeline > Delete Pipeline from drop-down menu

- src/test/java/school/redrover/PipelineProject5Test.java
> RF 00.02 refactoring class, add correct wait

- src/test/java/school/redrover/MultiConfiguration3Test.java
> RF 03.02 | Multi-Configuration > Disable project from Configuration page

- src/test/java/school/redrover/MultiConfiguration3Test.java
> RF 03.02 | Multi-Configuration > Check on Dashboard that project is disabled

- src/test/java/school/redrover/MultiConfigurationProject5Test.java
> AT_03.01 create and add description in MultiConfigurationProjectTest

- src/test/java/school/redrover/Pipeline8Test.java
https://trello.com/c/3WsAH7sT/1163-at-020301-pipeline-build-now-make-several-builds-at-the-same-time
> AT 02.03.01 Make several builds

- src/test/java/school/redrover/CreateMultiConfigurationProject2Test.java
> AT_03.01 addDescriptionInMultiConfigurationProjectTest

- src/test/java/school/redrover/FreestyleProjectAddDescription1Test.java
https://trello.com/c/GntHpaZ5/748-tc-0105-freestyle-project-add-description
> TC 01.05 | Freestyle project > Add description

- src/test/java/school/redrover/PipelineProject5Test.java
> 00.02 fix test pipeline

- src/test/java/school/redrover/FooterJenkinsVersionTest.java
> RF 13.01 | Footer > Jenkins version

- src/test/java/school/redrover/CreateOrganizationFolderTest.java
create testCreateOrganizationFolder()_NO
AT - https://trello.com/c/cdoIkNzg/1108-at-0006-new-item-organization-folder-create-new-organization-folder
> AT 00.06 | New Item > Organization Folder > Create new Organization Folder

- src/test/java/school/redrover/ProjectFolder2Test.java
RF - https://trello.com/c/ITRMb8bW
refactors assert: sort collections of expected and actual result and assert collections' equality
> RF 04.00| Folder > Create two folders

- src/test/java/school/redrover/FreestyleProject8Test.java
- src/test/java/school/redrover/NewViewTest.java
https://trello.com/c/80dTgWp3
 https://trello.com/c/NCP7Lkxr 
https://trello.com/c/CJIIFnvj
 https://trello.com/c/JYZFA2Z4
> AT 00.01 / AT 01.05 | New Item > Freestyle Project > add 4 tests

- src/test/java/school/redrover/NewItem2Test.java
RF https://trello.com/c/Ey4RUncp
remove Ignore, change test name, add waiter
> RF 00.00 | New Item > Create all types items

- src/test/java/school/redrover/PipelineProject1Test.java
> AT 02.07 |Pipeline > Rename > Rename Pipeline Project on the pipeline project page

- src/test/java/school/redrover/MultiConfigurationProjectVDTest.java
> AT 03.03 | Multi-Configuration > Create Multi-Configuration project

- src/test/java/school/redrover/BreadcrumbTest.java
- src/test/java/school/redrover/PipelineProject8Test.java
to PipelineProject8Test
RF - https://trello.com/c/nRErrs0J
> RF | Pipeline > Refactor class Pipeline2Test

- src/test/java/school/redrover/FreestyleProject26Test.java
> RF 00.01 | New Item > Freestyle Project, remove @Ignore

- src/test/java/school/redrover/MultibranchPipeline26Test.java
> AT 00.05 | New Item > Add test creating Multibranch Pipeline

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/Dvvld8ya/1213-at-0411-folder-create-organization-folder-in-folder
> AT 04.11 | Folder > Create Organization Folder in Folder

- src/test/java/school/redrover/FreestyleProject6Test.java
https://trello.com/c/lhqlZwij/1184-at-0003-new-item
> AT 01.05 | Freestyle project > Add description

- src/test/java/school/redrover/PipelineTest.java
> AT  02.03 | Pipeline > Build now > Testing pipeline building after changes in code.

- src/test/java/school/redrover/FreestyleProject8Test.java
https://trello.com/c/UoOY3bAG
https://trello.com/c/Z8WNVCUG
https://trello.com/c/NbiIkOu1
https://trello.com/c/6K463lOW
> AT 01.06 | Freestyle project > Rename project > add 4 tests

- src/test/java/school/redrover/CreateNewFolder1Test.java
AT - https://trello.com/c/J3uVjJYo/1002-%D0%B0%D1%82-0400-folder-create-folder
US - https://trello.com/c/bm8EO3Sf/17-us-0400-folder-create-folder
TC - https://trello.com/c/5W3Tlvag/161-tc-0400-folder-create-folder
> АТ 04.00 | Folder > Create Folder

- src/test/java/school/redrover/ConfigureFolder2Test.java
> AT 04.04 Folder > Configure Folder with Display Name

- src/test/java/school/redrover/UserProfileTest.java
AT - https://trello.com/c/8tOAWfw9
> AT 09.05 | Manage Users > Change the user profile > Edit email

- src/test/java/school/redrover/CreateFreestyleProject2Test.java
AT 01.01 | Freestyle project > View project page >Enable Freestyle Project from the Project Page and Verify Enabled Icon on Dashboard
[AT]-https://trello.com/c/IeOtWnkb/1230-at-0101-freestyle-project-view-project-page-enable-freestyle-project-from-the-project-page-and-verify-enabled-icon-on-dashboard
> AT 01.01 | Freestyle project > View project page > Enable Project

- src/test/java/school/redrover/ManageUsersTest.java
https://trello.com/c/D3qLjdTn/1103-rf-0000-item-sub-item
> RF 00.00 | ManageUsersTest > testMakeChangesToUserProfile

- src/test/java/school/redrover/MultiConfiguration3Test.java
> AT 03.07 | Multi-Configuration project > Rename Multi-Configuration project from drop-down menu on Config page

- src/test/java/school/redrover/MultiConfigurationTest.java
> AT_03.05 | Multi-configuration project > Configure > US title > Check the general parameters displayed and clickable

- src/test/java/school/redrover/PipelineJob1Test.java
> AT 02.04 | Pipeline > Disable Pipeline Job

- src/test/java/school/redrover/ConfigureGlobalSecurityTest.java
- src/test/java/school/redrover/MultiConfigurationTest.java
AT - https://trello.com/c/Hba3OBZz/1247-at-1801-configure-global-security-%D1%81hange-settings-and-save-them
1. added testCheckTitleTexts.
2. deleted getWait5() from old method.
> AT 18.01 Configure Global Security> Check Title Texts

- src/test/java/school/redrover/MultiConfigurationProjectTest.java
…figuration project
https://trello.com/c/usOu0DuF
> AT 03.02 | Multi-Configuration >Enable \ Disable project

- src/test/java/school/redrover/PipelineProject5Test.java
> AT 02.05 add delete pipeline with dropdown menu test

- src/test/java/school/redrover/OrganizationFolder26Test.java
> AT 00.06 | New Item > Organization Folder > Add test creating a new Organization Folder

- src/test/java/school/redrover/MultiConfigurationTest.java
> AT 03.06 | Delete Multi-Configuration project

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/NewItem2Test.java
> RF 04.00 | Folder > Create folder using invalid data

- src/test/java/school/redrover/FreestyleProject6Test.java
https://trello.com/c/TeXwtEnG/1262-at-0003-new-item
> AT 01.06 | Freestyle project > Rename project from Dashboard Page

- src/test/java/school/redrover/NewItemFreestyleProjectAllTest.java
> AT 00.01 | New Item>Freestyle Project>Create Freestyle Project with wildcard in the name

- src/test/java/school/redrover/DashboardTest.java
https://trello.com/c/YWo3jszB/1248-at-1201001-dashboard-line-dashboard-dropdown-menu-menu-is-shown-when-clicking-project-name-button
> AT 12.01.001 | Dashboard Line > Dashboard dropdown-menu > Menu Is Shown When Clicking Project Name Button

- src/test/java/school/redrover/DeleteUser1Test.java
> AT 15.05 | Users > User ID > Delete user

- src/test/java/school/redrover/PipelineProject9Test.java
https://trello.com/c/Ma7oDT3Z/1270-at-0002-new-item-pipeline-project
> AT 00.02 | create pipeline project

- src/test/java/school/redrover/FreestyleProject26Test.java
> AT 01.01 | Freestyle project > View project page > Add description to Freestyle project test

- src/test/java/school/redrover/PipelineProject2Test.java
Trello: [AT 00.02 | New Item > Create Pipeline Project > Sort Pipeline Project Alphabetically](https://trello.com/c/tlnnctqt/1279-at-0002-new-item-create-pipeline-project-sort-pipeline-project-alphabetically)
> Added testSortingPipelineProjectAplhabetically

- src/test/java/school/redrover/FreestyleProject8Test.java
https://trello.com/c/gOkIT18U
https://trello.com/c/YWXu2kuH
> AT 01.01 | Freestyle project > View project page > Verify Project is enabled / disabled

- src/test/java/school/redrover/FreestyleProject6Test.java
https://trello.com/c/5uuF4WZ8/1272-at-0106-freestyle-project-rename-project-from-project-page
> AT 01.06 | Freestyle project > Rename project from Project Page

- src/test/java/school/redrover/FreestyleProject26Test.java
AT https://trello.com/c/Cvz0oGmX
RF https://trello.com/c/V2Yrrvyj
> AT 01.01 | Freestyle project > Open Freestyle project page

- src/test/java/school/redrover/FreestyleProject01Test.java
Add testNameAndDescAreDisplayed + little REF(replace name of the freestyle project to const FREESTYLE_NAME) https://trello.com/c/Qa42FTBW/1289-us-0101-freestyle-project-view-project-page
> AT 01.01 | New Item > Freestyle Project > Create Freestyle Project

- src/test/java/school/redrover/Folder4Test.java
- src/test/java/school/redrover/model/FolderPage.java
> RF 00.00 | create FolderPage

- src/test/java/school/redrover/NewProject3Test.java
- src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/4mhuBsGu/1297-rf-refactor-class-newproject3test
> Refactor class

- src/test/java/school/redrover/FreestyleProject4Test.java
> AT 01.03 | Freestyle project > Build now

- src/test/java/school/redrover/FreestyleProject01Test.java
Add testEnableFreestyleProject
https://trello.com/c/BJdw20wt/1300-us-0101-freestyle-project-view-project-page-enable-project
> AT 01.01 | Freestyle project > View project page > Enable project      

- src/test/java/school/redrover/NewViewTest.java
ERR: https://trello.com/c/e3jdTKQi/1164-err-newviewtest-testcreatenewviewwithjobfilters
> RF ERR | NewViewTest > testCreateNewViewWithJobFilters

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/XD8Olcw0
Add new test testCreateFreestyleProjectGoingFromPeoplePage()
> AT 00.01 | New Item > Freestyle Project > Create Freestyle Project going from People page

- src/test/java/school/redrover/PageHeaderTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/NewJobPage.java
- src/test/java/school/redrover/model/PipelineConfigPage.java
- src/test/java/school/redrover/model/PipelinePage.java
https://trello.com/c/03pTLqhS/1313-rf-0002-new-item-create-pipeline-project
> RF 00.02 | New Item > Create Pipeline Project

- src/test/java/school/redrover/FreestyleProject4Test.java
> AT 01.03 | Freestyle project > Build project with Boolean parameter

- src/test/java/school/redrover/Folder5Test.java
> RF 04.03 | Folder > Move Folder to Folder

- src/test/java/school/redrover/PipelineJobTest.java
[RF](https://trello.com/c/1Gi1aEXf/1324-rf-0000-delets-locators-pipeline-job-test)
> delets_Locators_Pipeline_Job_Test

- src/test/java/school/redrover/MultiConfigurationProject4Test.java
> AT 00.03 | New Item > Multi - Configuration project >Create Multi-Сonfiguration project. Negative test-case

- src/test/java/school/redrover/MultiConfiguration3Test.java
> AT US 03.06 | Multi-Configuration project > Delete Multi-Configuration project from DropDownMenu

- src/test/java/school/redrover/FolderTest.java
https://trello.com/c/Bv6fPQTq
Refactoring testMoveFreestyleProjectToFolder()
> RF 04.12 | Folder > Move Freestyle Project to Folder > Move FreestyleProject to Folder by clicking Move link in side menu

- src/test/java/school/redrover/FreestyleProject2Test.java
- src/test/java/school/redrover/MultiConfigurationTest.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/ProjectPage.java
- src/test/java/school/redrover/model/RenameProjectPage.java
https://trello.com/c/aodGBFTc/1332-rf-0301-multi-configuration-project-pom
> updated Create, Rename Multiconfig tests to POM model, added POM defs

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/FreestyleProject2Test.java
- src/test/java/school/redrover/model/ProjectPage.java
> RF Rename method

- src/test/java/school/redrover/ConfigureGlobalSecurityTest.java
[AT] - https://trello.com/c/OYwiZowU/1355-at-1801-configure-global-security-check-number-of-titles-button
added testCheckNumberOfTitles
> AT 18.01 Configure Global Security | Check number of title's button

- src/test/java/school/redrover/FreestyleProject10Test.java
https://trello.com/c/Gg5kTYFx/1282-at-0001-new-item-freestyle-project-create-freestyle-project
> AT 00.01 | > Create Freestyle Project > from Dmitriy Zernov

- src/test/java/school/redrover/ConfigureGlobalSecurityTest.java
[AT] - https://trello.com/c/rR9Bvgh8/1356-at-1801-configure-global-security-check-number-of-help-buttons
added testCheckNumberOfHelpButtons
> AT 18.01 Configure Global Security | Check number of help buttons

- src/test/java/school/redrover/FreestyleProjectTest.java
TC https://trello.com/c/htt6Babu/671-tc-0101-freestyle-project-view-project-page-project-page-contains-only-the-name-of-project-without-description
AT https://trello.com/c/qo37Rknd/1368-at-0101-freestyle-project-view-project-page-project-page-contains-only-the-name-of-project-without-description
> AT 01.01 | Freestyle project > View project page >Project page contains only the name of project without description

- src/test/java/school/redrover/Folder4Test.java
- src/test/java/school/redrover/model/FolderConfigPage.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/NewJobPage.java
> RF 00.00 | POM > create FolderConfigPage

- src/test/java/school/redrover/MultiConfigurationProjectVDTest.java
> AT 03.07 | Multi-Configuration project > Rename MCP

- src/test/java/school/redrover/Folder8Test.java
- src/test/java/school/redrover/NewItem2Test.java
create **Folder8Test** class
remove _testCreateFolder()_ from **NewItem2Test** class to **Folder8Test** class 
rename _testCreateFolder()_ to _testCreateFolderWithoutDescription()_
RF: https://trello.com/c/x71nYcs1
> RF 04.00 | Folder > Create folder without description

- src/test/java/school/redrover/FreestyleProject3Test.java
- src/test/java/school/redrover/model/BuildPage.java
- src/test/java/school/redrover/model/FreestyleProjectPage.java
https://trello.com/c/RV15Kt3I/1369-rf-pom-create-freestyleproject-page-and-buildpage
> Create FreestyleProject Page and BuildPage

- src/test/java/school/redrover/Folder4Test.java
- src/test/java/school/redrover/HeaderTest.java
- src/test/java/school/redrover/model/FolderPage.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/NewViewFolderPage.java
- src/test/java/school/redrover/model/ViewFolderPage.java
> RF 00.00 | POM > create NewViewFolderPage, ViewFolderPage

- src/test/java/school/redrover/ManageJenkinsTest.java
> RF 09.02 | Manage Jenkins > Search settings > Search with numeric symbo

- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/model/FreestyleProjectPage.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/ManageJenkinsPage.java
- src/test/java/school/redrover/model/NewJobPage.java
> RF 09.02 | Manage Jenkins > rf testSearchNumericSymbol() to POModel

- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/PipelinePage.java
https://trello.com/c/8phGR92N/1383-rf-0201-pipelineview-pipeline-pagerename-pipeline
Transfer the test to the POM
remove two my tests
> RF 02.01 | Pipeline>View pipeline page>Rename Pipeline.

- src/test/java/school/redrover/Folder4Test.java
- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/FooterJenkinsVersionTest.java
- src/test/java/school/redrover/FreestyleProject12Test.java
- src/test/java/school/redrover/ManageJenkinsTest.java
- src/test/java/school/redrover/MultiConfigurationProject2Test.java
- src/test/java/school/redrover/MultiConfigurationTest.java
- src/test/java/school/redrover/NewProject3Test.java
- src/test/java/school/redrover/NewViewTest.java
- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/NewJobPage.java
+ Refactor test to POM
+ Change the method name to clickNewItem, as method names should start with a verb
> RF 00.01 FreestyleProject12Test.testCreateWithInvalidName

- src/test/java/school/redrover/MultiConfigurationTest.java
- src/test/java/school/redrover/model/ConfigurePage.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/MultiConfigurationProjectConfigPage.java
- src/test/java/school/redrover/model/ProjectPage.java
> RF 03.01 | Multi-configuration project > POM

- src/test/java/school/redrover/MultiConfigurationTest.java
- src/test/java/school/redrover/NewProject3Test.java
- src/test/java/school/redrover/model/FreestyleProjectConfigPage.java
- src/test/java/school/redrover/model/MultibranchPipelineConfigPage.java
- src/test/java/school/redrover/model/MultibranchPipelinePage.java
- src/test/java/school/redrover/model/NewJobPage.java
- src/test/java/school/redrover/model/OrganizationFolderConfigPage.java
- src/test/java/school/redrover/model/OrganizationFolderPage.java
https://trello.com/c/NYQsRPAG/1388-rf-pom-create-new-page
> RF | POM > Create new Page

- src/test/java/school/redrover/ConfigureFolder2Test.java
> AT 04.04 | Folder > Configure folder with description

- src/test/java/school/redrover/NewProject3Test.java
- src/test/java/school/redrover/model/BreadcrumbBarPage.java
- src/test/java/school/redrover/model/FolderConfigPage.java
- src/test/java/school/redrover/model/FolderPage.java
- src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/rQXtGKLY/1390-at-0400-folder-create-new-folder
> AT 04.00 Create new Folder

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/PipelinePage.java
> RF 02.01 | Pipeline>View pipeline page>delete Pipeline

- src/test/java/school/redrover/FreestyleProject3Test.java
- src/test/java/school/redrover/NewProject3Test.java
- src/test/java/school/redrover/model/BreadcrumbBarComponent.java
- src/test/java/school/redrover/model/BuildPage.java
- src/test/java/school/redrover/model/MultibranchPipelineConfigPage.java
- src/test/java/school/redrover/model/NewJobPage.java
https://trello.com/c/OkLDFFJn/1395-at-0005-new-item-create-new-multibranch-pipeline
> AT 00.05 Create new Multibranch Pipeline

- src/test/java/school/redrover/FreestyleProjectAllTest.java
> AT 01.01 | Freestyle project>Check to open view project page from the Dashboard

- src/test/java/school/redrover/MyViewsTest.java
> AT 11.03 |Views > New View >Edit View >Edit Description

- src/test/java/school/redrover/Folder4Test.java
- src/test/java/school/redrover/FreestyleProject12Test.java
- src/test/java/school/redrover/model/MainPage.java
Add test testCreatedProjectIsOnDashboard
Rename getJobName to getJobInList
Add method getJobName
> AT 00.01 | New Item > Freestyle project > Check created project on dashboard

- src/test/java/school/redrover/PipelineProject5Test.java
> AT 02.07 add rename pipeline from project page test

- src/test/java/school/redrover/PipelineProject5Test.java
> AT 02.07 add rename Pipeline by drop down menu test

- src/test/java/school/redrover/FreestyleProjectAllTest.java
> AT 01.01 | Freestyle project>View project page>Check visibility of project name and description

- src/test/java/school/redrover/MultiConfigurationProjectTest.java
- src/test/java/school/redrover/UserTest.java
- src/test/java/school/redrover/model/MultiConfigurationProjectPage.java
Reverts RedRoverSchool/JenkinsQA_06#2106
> Revert "RF 03.02 | Multi-Configuration >Enable \ Disable project"

- src/test/java/school/redrover/FreestyleProject4Test.java
> RF 01.03 | Freestyle project > Build now

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/model/FolderPage.java
- src/test/java/school/redrover/model/MultibranchPipelinePage.java
https://trello.com/c/Tmmg06ku/1413-at-0410-folder-create-multibranch-pipeline-in-folder
> AT 04.10 | Folder > Create Multibranch Pipeline in Folder

- src/test/java/school/redrover/HeaderTest.java
https://trello.com/c/WdGo3L0A/1376-at-1703-item-sub-item-title
> AT 17.03 | Page Header > Notifications Icon

- src/test/java/school/redrover/FreestyleProject16Test.java
- src/test/java/school/redrover/model/FreestyleProjectPage.java
- src/test/java/school/redrover/model/MainPage.java
RF 01.01 | Freestyle project > Disable/Enable Freestyle Project > Refactoring tests to POM
[RF] -https://trello.com/c/VG2TA4rC/1414-rf-0101-freestyle-project-disable-enable-freestyle-project-refactoring-tests-to-pom
> RF 01.01 | Freestyle project > Refactoring tests to POM

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/cgoXzumO/1411-at-0105-freestyle-project-add-description
> AT 01.05 | Freestyle project > Add description(Minor changes to Test)

- src/test/java/school/redrover/model/BuildPage.java
- src/test/java/school/redrover/model/ConfigurePage.java
- src/test/java/school/redrover/model/JobPage.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/ViewPage.java
- src/test/java/school/redrover/model/base/BasePage.java
- src/test/java/school/redrover/tests/BuildTest.java
> AT 02.03 | Pipeline > Configure Page > Pipeline Status check <Maksim2404>

- src/test/java/school/redrover/NewItemTest.java
- src/test/java/school/redrover/model/NewJobPage.java
[RF] - https://trello.com/c/PKO9q0Xo
refactoring old test
> RF 00.01 | POM > New Item > Error When Create Freestyle Project With Empty Name

- src/test/java/school/redrover/PipelineTest.java
- src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/CpI3hAqI
refactoring test
remove useless test
> RF 02.05 | Pipeline > Delete Pipeline from drop-down menu

- src/test/java/school/redrover/DeletePipeline3Test.java
- src/test/java/school/redrover/Pipeline10Test.java
AT 02.05 | Pipeline > Delete Pipeline > Delete Pipeline by drop-down item menu
https://trello.com/c/hnxk66Bz
> add test delete pipeline

- src/test/java/school/redrover/Footer2Test.java
- src/test/java/school/redrover/MyViewsTest.java
- src/test/java/school/redrover/model/ViewPage.java
https://trello.com/c/5nvXcNAD/1420-at-0000-item-sub-item-title
> AT 11.05 | View > My View > Add description

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/model/ManageJenkinsPage.java
https://trello.com/c/393k4e7v
Rewrite the testVerifyJenkinsVersionOnManageJenkinsPage using POM
> RF 13.01 | Footer > Verify Jenkins version on Manage Jenkins page

- src/test/java/school/redrover/FreestyleProject4Test.java
> RF 01.03 | Freestyle project > Build project with Boolean parameter

- src/test/java/school/redrover/MultiConfiguration3Test.java
> AT 03.02 | Multi-Configuration > EnableDisabled project

- src/test/java/school/redrover/FooterTest.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/RestApiPage.java
https://trello.com/c/y9GVOhsQ
Rewrite the testVerifyRESTAPILink using POM
> RF 13.02 | Footer > Verify REST API link

- src/test/java/school/redrover/Pipeline26Test.java
> RF 00.02| New Item > Create Pipeline Project > POM

- src/test/java/school/redrover/MultiConfigProject26Test.java
> RF 00.03 | New Item > Multi - Configuration project > Create Multi-Сonfiguration project

- src/test/java/school/redrover/FreestyleProject5Test.java
> AT 01.07 | Freestyle project > Delete project from Dashboard Page

- src/test/java/school/redrover/FreestyleProjectTest.java
https://trello.com/c/7U7CvymH/1455-rf-freestyleprojecttest-testenableproject
> RF FreestyleProjectTest > testEnableProject

- src/test/java/school/redrover/FreestyleProjectAllTest.java
> AT 01.01 | Freestyle project>View project page>Check enable project from view page

- src/test/java/school/redrover/FolderTest.java
- src/test/java/school/redrover/NewProject3Test.java
- src/test/java/school/redrover/OrganizationFolderTest.java
- src/test/java/school/redrover/model/FolderPage.java
- src/test/java/school/redrover/model/MainPage.java
- src/test/java/school/redrover/model/OrganizationFolderConfigPage.java
- src/test/java/school/redrover/model/OrganizationFolderPage.java
https://trello.com/c/0XcWlpLe
Refactoring to POM
> RF 04.11 | Folder > Create Organization Folder in Folder

- src/test/java/school/redrover/PipelineJobTest.java
[RF](https://trello.com/c/afhKN305/1450-rf-delets-locators-pipeline-job-test)
> RF_PipelineJobReplacementSelector

- src/test/java/school/redrover/MyViewsTest.java
- src/test/java/school/redrover/model/ViewPage.java
https://trello.com/c/eJPBIVst/1466-rf-1105-view-my-view-add-description
> RF 11.05 | View > My View > Add description

- src/test/java/school/redrover/NewProject3Test.java
- src/test/java/school/redrover/model/BreadcrumbBarComponent.java
- src/test/java/school/redrover/model/MainPage.java
https://trello.com/c/QYMGlOUj/1468-rf-class-newproject3test
> RF class newProject3Test

- src/test/java/school/redrover/NewViewTest.java
[AT 11.03 |Views > New View >Edit View>Help for feature: Description](https://trello.com/c/BHxvjBKC/1472-at-us-1103-views-new-view-edit-viewhelp-for-feature-description)
Тест проверяет совпадение текста в строке помощи.
> Add testHelpForFeatureDescription()

- src/test/java/school/redrover/CreateFreestyleProjectTest.java
- src/test/java/school/redrover/FreestyleProject01Test.java
https://trello.com/c/osySVYNc
remove test from CreateFreestyleProjectTest
transfer test to FreestyleProject01Test
> RF 00.01 | New Item > Freestyle Project > Create Freestyle Project with invalid name > refactoring to POM
